### ISSUE TITLE
GSlice: assertion failed: sinfo->n_allocated > 0

### ISSUE THREAD

**Issue by jverzani** [JuliaGraphics/Gtk.jl#131]
This code will consistently issue the following error after 1750 or so iterations in the i variable (1783, 1790, 1725, 1789 in sample runs):

```
 ***MEMORY-ERROR***: <unknown>[3125]: GSlice: assertion failed: sinfo->n_allocated > 0

 signal (6): Abort trap: 6
 __pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
 Abort trap: 6
```

The code is:

```
using Gtk

win = @GtkWindow()
sw = @GtkScrolledWindow()
b = @GtkBox(:v)
push!(win, sw); push!(sw, b)
showall(win)

for i in 1:1000
gc()
    println(i)
    empty!(b)
    for j in 1:50
        push!(b, @GtkButton("stress"))
    end
    showall(win)
end
```

Am I doing something wrong or is there an issue?

**Comment by PorcelainMouse** [comment]
Hmm, any idea what would cause this error when 'dnf' is nearly finished with an operation?  I was running this commandline tool in a terminal emulator in Xfce DE. I don't think any thing I did would have anything to do with Gtk.jl.  However, when a command completes, sometimes the DE will create a notification to the user.

Whatever the reason Gtk.jl was called, I have *never* seen this error before and I do this same action nearly every week.  Any more thoughts on what could cause this?
