### ISSUE TITLE
Use new call overloading

### ISSUE THREAD

**Issue by tknopp** [JuliaGraphics/Gtk.jl#134]
@vtjnash: Hi Jameson, if I get it right with Julia 0.4 we can have constructors even for abstract types. Do you think it would be feasible to get rid of the `@` names again? Or did I get this wrong...

**Comment by tknopp** [comment]
@vtjnash @timholy: Whats your your current thinking about this issue? I still think we should get rid of the exessive use of the macro syntax in Gtk.jl
Would the change be complicated to accomplish?

**Comment by vtjnash** [comment]
Should be a straigtforward matter of changing `macro` to `function` @ https://github.com/JuliaGraphics/Gtk.jl/blob/master/src/GLib/gtype.jl#L221. I would definitely merge any PRs to fix this.

**Comment by tknopp** [comment]
I tried 
```
        function $einame(args...)
            Expr(:call, $ename, map(esc,args)...)
        end
```
and
```
        function $einame(args...)
            call( $ename, map(esc,args)...)
        end
```
but neither worked. But this might still be because of my still non-existing macro foo.

**Comment by fcard** [comment]
@tknopp, `esc` is a `Expr` manipulation function, and `call` is deprecated, so it should probably be...

```
function $einame(args...)
  $ename(args...)
end
```

**Comment by tknopp** [comment]
yes thanks, that works. I needed to let the current macro definition stay there because lots of code with Gtk.jl uses the `@` syntax. But it seems to be clever anyway to remove the `@` syntax a little later in order to not break other packages relying on it.
