### ISSUE TITLE
Cannot open multiple files with open_dialog

### ISSUE THREAD

**Issue by rowlesmr** [JuliaGraphics/Gtk.jl#190]
`open_dialog("Pick some files", select_multiple=true)` fails to allow for the selection of multiple (or single) files.

If a files (or file) are selected, and "Open" is pressed, I get the following error:

```
ERROR: MethodError: `convert` has no method matching convert(::Type{Ptr{Gtk.GLib
._GSList{UInt8}}}, ::GList{Gtk.GLib._GSList{UInt8} => UInt8})
This may have arisen from a call to the constructor Ptr{Gtk.GLib._GSList{UInt8}}
(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Ptr{T}}, ::UInt64)
  convert{T}(::Type{Ptr{T}}, ::Int64)
  ...
 in open_dialog at c:\jpkg\v0.4\Gtk\src\selectors.jl:86
 in open_dialog at c:\jpkg\v0.4\Gtk\src\selectors.jl:73
```

If I press Cancel prior to pressing Open, then `0-element Array{UTF8String,1}` is printed to the console.

Explicitly setting `select_multiple=false` doesn't affect choosing a single file.

I'm using Windows 7, Service pack 1, 64 bit.
I've tried in on Julia 0.3.11 & Gtk 0.8.6 and Julia 0.4.0-rc3 & Gtk 0.9.2

I am running it in REPL. I have entered `using Gtk` and `using Gtk.ShortNames`.

**Comment by alhirzel** [comment]
This is still an issue on the latest version.

**Comment by alhirzel** [comment]
If you unroll the code in selectors.jl, you can get an error in REPL:


```
julia> x = Gtk.open_dialog("whatever", select_multiple=true)
julia> y = ccall((:gtk_file_chooser_get_filenames,Gtk.libgtk), Ptr{Gtk._GSList{UInt8}}, (Ptr{GObject},), x)
julia> Gtk.GLib.GList(y)
2-element Gtk.GLib.GList{Gtk.GLib._GSList{UInt8},UInt8}:
Error showing value of type Gtk.GLib.GList{Gtk.GLib._GSList{UInt8},UInt8}:
	ERROR: InexactError()
```

**Comment by tknopp** [comment]
ping @vtjnash: I am not very familiar with the GList stuff. Could you have a look?
