### ISSUE TITLE
Non-REPL usage

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Gtk.jl#195]
Breakage reported [here](http://stackoverflow.com/questions/33549485/julia-gtk-windows-do-not-display-outside-repl). I've verified it (even if you add `showall(win)`).

**Comment by hustf** [comment]
Not quite the same symptoms, but perhaps same cause as for #165?

**Comment by vtjnash** [comment]
yep, looks like without isinteractive, the code no longer creates the gtk_main task automatically (https://github.com/JuliaLang/Gtk.jl/commit/b56e8da9ac52ada6b7a526facb0b9df900832514#diff-0000751d49843767d583b66145fa8b46R18)

**Comment by astrieanna** [comment]
Is this going to be fixed soon?
If not, would altering the section of the readme that talks about how to make Gtk things work without the REPL to contain the solution from StackOverflow be an improvement?

**Comment by paulmelis** [comment]
This issue appears to be still there with Julia 1.5.3 and 1.6 RC1. I indeed found the stackoverflow post mentioned by OP to figure out why no window was shown by my Gtk.jl script.

Apart from that, even the example from the [Getting Started](https://juliagraphics.github.io/Gtk.jl/latest/manual/gettingStarted/) section in the docs does not work outside the REPL without adding `Gtk.gtk_main()`. And the docs contain no mention of `gtk_main` when searching for it. The only other [mention of non-REPL use](https://juliagraphics.github.io/Gtk.jl/latest/manual/nonreplusage/#Non-REPL-Usage-1) of scripts using Gtk.jl are for handling premature closure of a window at the end of a script.

**Comment by tknopp** [comment]
fixed here: https://github.com/JuliaGraphics/Gtk.jl/blob/master/docs/src/manual/nonreplusage.md

but unfortunately the docs do not deploy right now. :-(

**Comment by tknopp** [comment]
ok, docs are now updated. This now can be closed.
