### ISSUE TITLE
push!(::StyleContext, ::CssProvider, ::Int) throws a method error.

### ISSUE THREAD

**Issue by fcard** [JuliaGraphics/Gtk.jl#205]
On theme.jl, a method `push!(::StyleContext, ::StyleProvider, ::Int)` is defined, but `CssProvider` is not a subtype of `StyleProvider`.

``` julia
using Gtk.ShortNames

l = @Label "I am some blue text!"
c = Gtk.GAccessor.style_context(l)
p = CssProviderLeaf(data="GtkLabel {color:blue}")
push!(c, p, 600)
```

``` julia
ERROR: MethodError: `push!` has no method matching push!(::Gtk.GtkStyleContextLeaf,
 ::Gtk.GtkCssProviderLeaf)
Closest candidates are:
  push!(::Any, ::Any, ::Any)
  push!(::Any, ::Any, ::Any, ::Any...)
  push!(::Array{Any,1}, ::ANY)
  ...
 in push! at abstractarray.jl:1393
```

**Comment by vtjnash** [comment]
StyleProvider is an Interface, so it has no subtypes (https://developer.gnome.org/gtk3/stable/GtkStyleProvider.html#GtkStyleProvider-struct)

You should be able to dispatch with it via `push!(c, StyleProvider(p), 600)` (which is essential for the autogenerated code)

in this case, it seems to me the hand-written type-assert didn't need to be as strict

**Comment by fcard** [comment]
Got you, that works. It does feel a bit unjulian to cast a value to its "interface" though, should the type-assert just be removed? The only other thing that can be added to a StyleContext is a style class, and I don't think `push!` is appropriate to do that.

**Comment by nlw0** [comment]
I cannot make this work in the current version, there are no errors, althought the text is not blue either. Any major related changes in the libary?
