### ISSUE TITLE
open_file segmentation fault

### ISSUE THREAD

**Issue by tknopp** [JuliaGraphics/Gtk.jl#211]
I get a segmentation fault on previously working code:

```
function testApp()
  btnOpenFile = @Button("Load")
  win = @Window(btnOpenFile, "TestApp", 800,600)

  signal_connect(btnOpenFile, "clicked") do widget
    filename = open_dialog("OpenFile", action=GtkFileChooserAction.SELECT_FOLDER)
    println(filename)
  end

  showall(win)
end
```

The segmentation fault happens at `open_dialog`. This is on Julia 0.4.2 on a mac.

**Comment by tknopp** [comment]
Hm works on linux.

**Comment by lobingera** [comment]
What is the gtk version and how did you install the libraries?

**Comment by tknopp** [comment]
Pkg.add("Gtk") 

version of `Gtk.jl` is  0.9.3.
Gtk through Homebrew.jl is 3.19.1

**Comment by tknopp** [comment]
I cannot reproduce this with @vtjnash recent commits and thus close this. Yay
