### ISSUE TITLE
GtkFileFilter construction fails in julia 0.4

### ISSUE THREAD

**Issue by Matt5sean3** [JuliaGraphics/Gtk.jl#247]
Within julia 0.4 the `GtkFileFilter` fails due to a MethodError. Within julia 0.4 the empty string literal, `""`, is an `ASCIIString` but `Gtk.String`, which seems to be a shim for the string changes in julia 0.5, is a `UTF8String`. The default values utilize the empty string literal which causes type checking to fail.

This issue arises in both `v0.10.1` and the `master` branch.

**Comment by Matt5sean3** [comment]
Switching from `String` to `AbstractString` seems to fix the problem with minimal issues and doesn't reintroduce warnings in julia 0.5 from what I'm seeing. If the concrete type needs to be ensured the arguments could be passed through a conversion to make sure the type is correct.

I'll probably create a pull request with this fix later today.

**Comment by Matt5sean3** [comment]
Anyone else experiencing this can use this work-around until the problem is solved. Pattern and mimetype must be set explicitly, their default arguments cause failure. Using just a string for a filter in `open_dialog` will still fail even if it's a UTF8String because the mimetype default argument will still cause a `MethodError`

```julia
filter = @GtkFileFilter(pattern=UTF8String("*.csv"), mimetype=UTF8String("text/csv"))
file_path = open_dialog("Open a File", GtkNullContainer(), (filter, ))
```

**Comment by tknopp** [comment]
I can confirm this issue. Question is a little how this will work in julia 0.5 where `String` is again a concrete type.

**Comment by Matt5sean3** [comment]
`AbstractString` still exists in 0.5, or at least in 0.5-rc3. From there, force conversion to the `String` type to guarantee compatibility with C. The `String` type is defined locally in the Gtk package, via compat I think, so this is a conversion to a UTF8String in 0.4, which I'm not sure how well C deals with. This is how I solved it in my pull request at least.

**Comment by Matt5sean3** [comment]
The fix has been merged in with test cases to prevent the problem from reoccurring so I'll close the issue.
