### ISSUE TITLE
Display an image?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaGraphics/Gtk.jl#249]
How can I display an image using Gtk.jl? I haven't found any documentations about it.

**Comment by lobingera** [comment]
There are various options. You can put a GtkCanvas into a window or use GtkImage. I agree, there should be an example for non-Gtk experts in doc.

**Comment by timholy** [comment]
If you use GtkUtilities you can just `copy!` it onto a Canvas. https://github.com/timholy/GtkUtilities.jl/blob/99d837f559536eafafd507ffa46e9b25523eda10/src/GtkUtilities.jl#L53

**Comment by lobingera** [comment]
i have no local julia installation right now, but my own (old) example was
```
julia> using Gtk
julia> i = Gtk.@GtkImage("../.julia/v0.3/Cairo/samples/data/mulberry.png");
julia> w = Gtk.@GtkWindow(i,"title");
julia> show(i);
```


The image shows up only with the show(i).

**Comment by lobingera** [comment]
@AStupidBear: Did you succeed?

**Comment by AStupidBear** [comment]
@lobingera @timholy Thank you for your suggestions!
I have successfully used GtkUtilities.copy! to display an image.
Lobingera's method also works, but what I want is displaying an image stored in memory.

**Comment by Kelvyn88** [comment]
Hi, 

Canvas has support to load svg files? or mayber GtkImage is better?

Any suggestion would be gratefully.

**Comment by Kelvyn88** [comment]
I found the Rsvg package to convert SVG to PNG and use it in GtkCanvas. 

Thanks
