### ISSUE TITLE
add a file selector button to the example

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaGraphics/Gtk.jl#261]
I don't know where to look to see how to use it

**Comment by lobingera** [comment]
Could you please provide more context? Where would your 'file selector button' be added?

![snapshot8](https://cloud.githubusercontent.com/assets/5199059/19408263/596be896-92b9-11e6-8759-7f4a0a68027d.png)

**Comment by JeffreySarnoff** [comment]
Thanks for being so responsive.  If that screen you show is something that is part of the examples you discuss -- tell me where to find it. When I was looking at the code to see what widgets, manners of interaction, and artfulness you have made available, I just did not see it.  

I did notice capacities for which proper use was unclear.  I get that you have wrapped indirection and that serves a good organization,  I used Gtk a long time ago, through Python.  Then I moved to Qt because at that time it was more capable in a few ways.  I recall no specifics, so any direction or helpful hints are welcome.

**Comment by tknopp** [comment]
@JeffreySarnoff 

Is this what you are looking for:
https://github.com/JuliaGraphics/Gtk.jl#file-dialogs

**Comment by tknopp** [comment]
Tim Holy has made little wrappers around `GtkFileChooser` which make them a little easier to use.

**Comment by JeffreySarnoff** [comment]
That is it .. thank you.  Is this all of a simple pattern, could I parrot what Tim did for GtkFileChooser with other widget/ui elements and expect it to work?

**Comment by tknopp** [comment]
If you mean by `parrot` to build high level functions around more low level Gtk routines then sure that will of course work. I have recently programmed a larger application using Gtk.jl and one key thing that helped me was using `GtkBuilder` in combination with `glade`. When you do that all the construction of the widgets is automatically done and the interaction with Gtk.jl is pretty minimal, i.e. the code is pretty clean without any boilerplate.

**Comment by tknopp** [comment]
I am closing this as the requested documentation is actually already there.
