### ISSUE TITLE
Need a new tag

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphics/Gtk.jl#262]
Just letting you know that the package is emitting a warning during the build.

**Comment by tknopp** [comment]
@juliohm why did you close this?

**Comment by juliohm** [comment]
@tknopp because the issue was solved in master, do we need to leave it open anyways?

**Comment by tknopp** [comment]
yes the issue is solved but @yuyichao changed the title to `Need a new tag`, which is not yet addressed. So this is a good reminder that Gtk.jl needs a new release.

**Comment by juliohm** [comment]
Got it, well, this should be quick to do. Feel free to close it when appropriate.

**Comment by juliohm** [comment]
Can you confirm this issue can be closed now?

**Comment by tknopp** [comment]
yes thanks for the reminder. I went ahead and do the tags
