### ISSUE TITLE
A small scrollable window with a lot of buttons

### ISSUE THREAD

**Issue by DanielHarasim** [JuliaGraphics/Gtk.jl#269]
Hello,

I'm totally to Gtk and GUI programming in general and hope that someone can help me with this problem:

I want to create a GUI with a lot of buttons similar to

```julia
using Gtk
g = @GtkGrid()
w = @GtkWindow(g)
n = 10
for i in 1:n, j in 1:n
    g[j,i] = @GtkButton("$i $j")
end
showall(w)
```
with n >= 100. The problem is that the window is for large n bigger than my screen, but I don't know how to reduce its size and add scroll bars instead.

Thank you in advance!

**Comment by tknopp** [comment]
```
using Gtk
g = @GtkGrid()
s = @GtkScrolledWindow(s)
w = @GtkWindow(s)
n = 10
for i in 1:n, j in 1:n
    g[j,i] = @GtkButton("$i $j")
end
showall(w)
```

I can recommend to use glade in combination with GtkBuilder to make as much as possible of the UI without any code. In my application I only code those things that require a dynamic UI update.

**Comment by tknopp** [comment]
And even more important using Glade helped me understanding the Layout management of Gtk. One can easily play around and get a preview how things will look /behave.

**Comment by yuyichao** [comment]
I assume this is more of a question for the julia-users list than a package issue.

**Comment by tknopp** [comment]
yes, although julia-users is sometimes a little indirect since it covers all of Julia.

**Comment by DanielHarasim** [comment]
Thank you very much! I tried the `@GtkScrolledWindow()` macro without using an additional `@GtkWindow()` and was wondering why it didn't work...

I will also have a look at Glade.
