### ISSUE TITLE
WARNING:  Gtk.GConstants.GtkIconSize.(:MENU) is deprecated;

### ISSUE THREAD

**Issue by TravisA9** [JuliaGraphics/Gtk.jl#270]
Hey guys, I'm not sure if this is my fault or a problem that needs to be fixed in GTK.jl. This warning showed up around the time that julia turned 0.5 and I have been ignoring it up 'til now. This is the line of code producing the warning:
```julia
imClose = @Image(stock_id="gtk-close",size=:MENU)
```
And here is where the problem is reported:
.julia/v0.5/Gtk/src/displays.jl:277

code:
```julia
        img = ccall((:gtk_image_new_from_stock,libgtk),Ptr{GObject},(Ptr{UInt8},Cint),bytestring(stock_id),GtkIconSize.(size))
```

**Comment by TravisA9** [comment]
The warning doesn't show up after making the following modification.
## WAS:
```julia
        img = ccall((:gtk_image_new_from_stock,libgtk),Ptr{GObject},(Ptr{UInt8},Cint),bytestring(stock_id),GtkIconSize.(size))
```
## NOW:
```julia
       img = ccall((:gtk_image_new_from_stock,libgtk),Ptr{GObject},(Ptr{UInt8},Cint),bytestring(stock_id), getfield(GtkIconSize, size))
```

### In the julia docs is says:

> ```julia 
> getfield(value, name::Symbol)
> ```
> Extract a named field from a value of composite type. The syntax a.b calls getfield(a, :b).

If this needs to be changed, there are other similar lines in the same function that should also be updated.

**Comment by tknopp** [comment]
yes seems correct. Could you change these and make a pull request?

**Comment by TravisA9** [comment]
Sure!

**Comment by TravisA9** [comment]
Ok, I found two lines with that syntax and issued a pull request. Thanks fro the quick response.

**Comment by tknopp** [comment]
thanks!
