### ISSUE TITLE
Create Documentation based on Documenter.jl

### ISSUE THREAD

**Issue by tknopp** [JuliaGraphics/Gtk.jl#273]
I think we should move the documentation to a Documenter.jl based approach. The docs of the Python Gtk bindings (https://python-gtk-3-tutorial.readthedocs.io/en/latest/install.html) are pretty good in my opinion and it might be a good idea to organize the docs in a similar way.

**Comment by tknopp** [comment]
I will go ahead and push some initial stubs. As one can see here: https://github.com/JuliaDocs/Documenter.jl/issues/392 Gtk.jl already pushed Documenter.jl to the limits

**Comment by tknopp** [comment]
I have not enough rights to setup Documenter.jl (i.e. add the public keys) to Github. Help? @timholy @vtjnash @tkelman

**Comment by tkelman** [comment]
I raised your permissions to admin on this repo

**Comment by tknopp** [comment]
Thanks Tony!

**Comment by tknopp** [comment]
Wow, its working: http://juliagraphics.github.io/Gtk.jl/latest/
This is my first time experience with Documenter.jl and its just fun.

**Comment by vtjnash** [comment]
Wow, that does look spiffy!

**Comment by tknopp** [comment]
Well, its just Documenter.jl doing all the work. But I would like to take this as an opportunity making the docs of Gtk.jl better, especially for beginners. But at the same time we should think about some API streamlining (#274).

**Comment by tknopp** [comment]
this is basically done now. Needs some fixing though

**Comment by giordano** [comment]
This can be closed
