### ISSUE TITLE
GdkQuartzDisplay does not implement the monitor vfuncs

### ISSUE THREAD

**Issue by jminardi** [JuliaGraphics/Gtk.jl#278]
I am using Julia 0.5 on OS X 10.12

I get the following error when I try to use ProfileView: 

GdkQuartzDisplay does not implement the monitor vfuncs

If I just Profile.print() I can see the tree so I know the profiler works.

@timholy suggested I post the error here.

**Comment by tknopp** [comment]
https://github.com/Homebrew/brew/issues/1219

?

**Comment by vtjnash** [comment]
that's merely an informational statement, not a bug (and not an issue)

**Comment by jminardi** [comment]
Ok so you are saying the fact that the flame graph doesn't show is unrelated to the error message?

**Comment by vtjnash** [comment]
It's not an error message. It's prefixed with "warning", but it's really just an informational statement (well, a TODO message curtesy of the Gdk developers).
