### ISSUE TITLE
Force to redraw Gtk Window

### ISSUE THREAD

**Issue by ronisbr** [JuliaGraphics/Gtk.jl#280]
Hi guys!

I have a simulator that computes a differential equation. I want to build a Gtk window to show the progress. Inside the solver, there is a function which is called at every simulation second.

Inside this function, I am modifying the progress bar property. However, the Gtk window is not being updated. The only think I could do to make it work is to add a `sleep(0.0001)` after I set the progress bar property. Hence, I would like to know if there is a function to force the Gtk window to be repainted or if there is a better way to do this.

**Comment by tknopp** [comment]
I am not fully sure what you setting is, but updating a progressbar while a simulation is running is a little bit more complicated currently since Julia does not provide background threads.

I made here an example of a fully asynchronous application that uses two processes:

http://juliagraphics.github.io/Gtk.jl/latest/manual/async.html

This is more hacked together since I am not an expert in this area.

**Comment by ronisbr** [comment]
Hi @tknopp 

Yes, I saw this example. But I always getting the same result. If I do not add a `sleep` after setting the process, julia does not update the Gtk window during the simulation.

**Comment by ronisbr** [comment]
Ah btw! I don't mean just a progress bar, the Gtk window is not update at all, even after a resizing.

**Comment by ronisbr** [comment]
For example, even this simple code is not working:

```julia
using Gtk

win = @GtkWindow
label = @GtkLabel("Progress 0.0%")
push!(win,label)
showall(win)
progress = 0.0

@async begin
    while(true)
        setproperty!(label, :label, "$(progress = progress + 1.0)")
        sleep(1)
    end
end
```

The label starts to being updated every 1s until the simulation is started, which is a ODE being solved by DifferentialEquations package. After that, the Gtk window becomes unresponsive.

**Comment by tknopp** [comment]
Yes this is expected if you do things in the UI thread. 

So if your UI is freezing you are doing work in the UI thread. Adding sleep will allow to switch the task and update the UI. So adding sleeps can work but from my perspective does not work always perfect. Therefore, the suggestion to do the work in a different process.

**Comment by ronisbr** [comment]
@tknopp I see, but why my last code is not being executed in a different process?

**Comment by vtjnash** [comment]
you can call `reveal(widget, true)` to force it to render the screen immediately:
https://github.com/JuliaGraphics/Gtk.jl/blob/a62c03386de95cc133a333df8e1ba891c815f031/src/events.jl#L108
(otherwise, it queues up all drawing and waits for processing to stop to handle all client updates)

**Comment by tknopp** [comment]
`@async` does by default not spawn a new process. You have to make it with `@spawn` and first `addprocs`.

**Comment by tknopp** [comment]
@vtjnash But while this redraws the progress bar this is not really keeping the UI responsive. Work should be done in an asynchronous fashion. I dream that we could spawn a thread for that...

**Comment by vtjnash** [comment]
As tknopp suggested, another approach is to create a worker with `p = addprocs(1)`, schedule the work with `@spawnat p solver()`, and then periodically update the counter on the master node (you may also need to insert periodic calls to  `yield()` to allow it to flush messages).

**Comment by tknopp** [comment]
(Actually this use case was the reason I initially started with multithreading in Julia)

**Comment by ronisbr** [comment]
@tknopp @vtjnash thanks guys!

Using your suggestions, I could make this working by adding a process and starting Gtk inside it.

The value of progress bar is changed between the processes using a shared array, is there a better option?

**Comment by tknopp** [comment]
currently not, but it is planned that Julia supports free running threads at some point

**Comment by ronisbr** [comment]
Good @tknopp !

Thanks! I think we can close this bug :)
