### ISSUE TITLE
How can I use key press function?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaGraphics/Gtk.jl#283]
I want to use key press event in a GUI. I have found GdkEventKey object in [gdk.jl ](https://github.com/JuliaGraphics/Gtk.jl/blob/d39896726bedac6415b1c05764b336f92508b294/src/gdk.jl#L130) but I don't know how to use it. Can somebody provide a simple example?

**Comment by lobingera** [comment]
https://github.com/timholy/GtkUtilities.jl implements key events in the pan/zoom functionality, see this as example.

As with any event in Gtk/Gdk you need to connect to the signal a handler that reads the signal and interprets it. Note: you will only get key events for certain widgets.

**Comment by tknopp** [comment]
Here, is the particular example:

https://github.com/timholy/GtkUtilities.jl/blob/master/src/panzoom.jl#L262

in GtkUtilities.jl. Would be great to have a small example on this in our new documentation system.

**Comment by lobingera** [comment]
Simple example (key-press in window)
```
julia> e = Gtk.GtkWindow("title");

julia> id1 = signal_connect(e, "key-press-event") do widget, event
           println("You pressed key ", event.keyval)
       end
0x000000000000006d

julia> You pressed key 104
You pressed key 107
You pressed key 97
You pressed key 115
You pressed key 100
You pressed key 104
You pressed key 105
You pressed key 117
You pressed key 118
You pressed key 97
```

**Comment by tknopp** [comment]
Thanks, I added this to the documentation:

https://github.com/JuliaGraphics/Gtk.jl/blob/master/docs/src/manual/keyevents.md

The documentation could be improved here by discussing key combinations (copy, past, ans so on)

**Comment by lobingera** [comment]
@tknopp Actually, it's a quite uncomplete example, as you get back the keycode, and it's missing a convert back to the 'key'. Also not all Widgets support the key-events (and i learned that Gtk.jl is missing the EventBox).

**Comment by tknopp** [comment]
yes, this is a first stub and seeks for proper/more documentation.

**Comment by AStupidBear** [comment]
@lobingera Thanks
