### ISSUE TITLE
GSoC Project

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGraphics/Gtk.jl#284]
The GSoC proposal current mentioned on the [website](https://github.com/JuliaLang/julialang.github.com/blob/master/soc/projects/graphics.md#gtkjl-improvements) looks out of the date (and is a little vague to begin with). Are the issues mentioned still relevant? If not, are there other well-defined projects a student could work on? Do we have anyone who would be able to mentor such a project?

**Comment by tknopp** [comment]
these things are actually solved (since a long time). I think we should remove that from the GSoC page. I would love if someone could work on Gtk.jl but I won't be really capable of mentoring this.

**Comment by MikeInnes** [comment]
Thanks for your reply – with that being the case I've gone ahead and removed it for now. A new proposal is more than welcome but will need a potential mentor.
