### ISSUE TITLE
build issues on Ubuntu 16.04 (wrong apt package specified?)

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaGraphics/Gtk.jl#289]
I found that, on Ubuntu 16.04, the package only builds correctly when `libgtk-3-dev` is installed from apt-get, while the deps script tries to install `libgtk-3-0`.

Looking at their contents, `libgtk-3-0` provides the file `/usr/lib/x86_64-linux-gnu/libgtk-3.so.0`, while `libgtk-3-dev` provides `/usr/lib/x86_64-linux-gnu/libgtk-3.so`. Only the latter makes the build script happy. (In fact, they are both just symlinks to the same file though.)

Furthermore, when not finding the desired library the script tried to invoke `sudo apt-get install libgtk-3-0` (which would not have worked anyway for the reasons stated above, in fact it was installed already on my system), which resulted in the following error:

```
INFO: Building Gtk
Installing dependency libgtk-3-0 via `sudo apt-get install libgtk-3-0`:
sudo: no tty present and no askpass program specified
======================================================================[ ERROR: Gtk ]=======================================================================

LoadError: failed process: Process(`sudo apt-get install libgtk-3-0`, ProcessExited(1)) [1]
while loading /home/carlo/.julia/v0.6/Gtk/deps/build.jl, in expression starting on line 61
```

I guess this may be a problem with BinDeps, though?

**Comment by tkoolen** [comment]
I ran into the same issue. Thank you for the workaround, @carlobaldassi.
