### ISSUE TITLE
Icons not found

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaGraphics/Gtk.jl#292]
I'm not sure what changed but some icons do not work anymore on OS X. 

```julia
b = GtkToolButton("gtk-save-as") 

win = GtkWindow(b)

showall(win)

(<unknown>:47866): Gtk-WARNING **: Error loading theme icon 'edit-find' for stock: Icon 'edit-find' not present in theme Adwaita
```

It might be because "gtk-save-as" is deprecated in Gtk, using "document-save-as" instead doesn't throw a warning but no icon is displayed instead.

**Comment by tknopp** [comment]
I think there was some Homebrew.jl issue about this

**Comment by tknopp** [comment]
https://github.com/JuliaGraphics/Gtk.jl/issues/180#issuecomment-282029796

**Comment by tknopp** [comment]
Could you try this?

**Comment by jonathanBieler** [comment]
My bad I should have searched better, the `Homebrew.add("gnome-icon-theme")` fixes it. Maybe that should be included in the build process to make sure it's installed.

**Comment by tknopp** [comment]
As long as this is fixed its absolutely good to report the issue. Not sure what the proper fix is.

**Comment by timholy** [comment]
Pull request? Only folks with macs can really test such PRs, and it may be the case that none of the primary developers of this package are mac users. (I'm certainly not.)

**Comment by tknopp** [comment]
I can test on a mac. The issue here is, however, an Homebrew thing where I am no expert for.

**Comment by jonathanBieler** [comment]
I would just insert a `Homebrew.add("gnome-icon-theme")` [here](https://github.com/jonathanBieler/Gtk.jl/blob/master/deps/build.jl#L53) but I don't really understand how BinDeps works so that might not be the correct solution.

**Comment by tknopp** [comment]
Does not hurt there. So +1 for a PR ;-)
