### ISSUE TITLE
How to build a Window that includes a MenuBar as well as other widgets?

### ISSUE THREAD

**Issue by yakir12** [JuliaGraphics/Gtk.jl#301]
I'll gladly update the documents if I knew how to build a `Window` with a `MenuBar` **and** anything else (e.g. `Frame`, `Button`, `Label`, and/or `Grid`).

**Comment by tknopp** [comment]
you have to put the MenuBar into a Box first.

**Comment by tknopp** [comment]
So a box with two rows, the first has the MenuBar and the second has the actual content.
