### ISSUE TITLE
syntax: prefix "$" in non-quoted expression

### ISSUE THREAD

**Issue by dryden3** [JuliaGraphics/Gtk.jl#306]
val = $(G_.value(current))
  tic()
  NN_Control(val)
  time = toc()
  mystring = "Time: $time"
  setproperty!(Time,:text,String(eval(mystring)))
Time is an entry.
I started off with just my string than added one on at a time. It still does not work. 
Any help would be greatly appreciated!

**Comment by vtjnash** [comment]
```
julia> val = $(G_.value(current))
ERROR: unsupported or misplaced expression $
```
I assume you meant to drop this `$`?

```
eval(mystring)
```
er, mystring is "Time: $time", what do you expect this do return?

**Comment by dryden3** [comment]
Indeed I did. 
Thanks
