### ISSUE TITLE
When Loading Gtk, representation of BigFloats depends on locale language

### ISSUE THREAD

**Issue by giordano** [JuliaGraphics/Gtk.jl#308]
```julia
$ LANG="it_IT.UTF-8" julia 

julia> big(1.0)
1.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> using Gtk

julia> big(1.0)
1,000000000000000000000000000000000000000000000000000000000000000000000000000000
```
This happens only for `BigFloat`s, no problem with `Float64`.  For sure `LANG` is relevant here (in Italian comma is the decimal separator), because when setting `LANG=C` there is no problem:
```julia
$ LANG=C julia 

julia> big(1.0)
1.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> using Gtk

julia> big(1.0)
1.000000000000000000000000000000000000000000000000000000000000000000000000000000
```
The locale must be set in the shell before running Julia, changing it within Julia with `ENV["LANG"] = "C"` has no effect.  I can reproduce this issue with Julia 0.5 and 0.6 (built yesterday).

**Comment by tknopp** [comment]
This is because Gtk does change the locale setting. First Julia sets it to C then Gtk switches back to whats defined in the console.

Here is what we have done to solve this for regular Float parsing:

https://github.com/JuliaLang/julia/issues/5928

So in my point of view this is not a Gtk issue but a Julia issue. BigFloat parsing should be locale-independent!

**Comment by yuyichao** [comment]
FWIW seems to be a printing issue and not a parsing issue.

**Comment by tknopp** [comment]
ah yes, sorry. But still our printing of big floats should be locale-independent.

**Comment by giordano** [comment]
So I should file an issue in Julia?

**Comment by tknopp** [comment]
yea, but it would be great to have a more reduced case that is independent of Gtk. One could try reproducing it by `ccall`-ing the `setlocale` function from within Julia.

**Comment by giordano** [comment]
> then Gtk switches back to whats defined in the console.

Can you please point me to where this is done in `Gtk.jl`, in order to craft a minimal example?  Grepping `setlocale` doesn't help me.

**Comment by tknopp** [comment]
```
julia> ccall((:setlocale,"libc"), Cstring,(Cint,Cstring),0,"de_DE" )
Cstring(0x00007fc083502b80)

julia> big(1.00000000000000000000000000000000000000000000000000000000)
1,000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by tknopp** [comment]
its done with the c-code within Gtk. Thus we cannot change it.

**Comment by giordano** [comment]
Ah, I see, I thought it was done in `Gtk.jl`, not the Gtk library.  Thanks.

**Comment by giordano** [comment]
Uhm, I can't reproduce the error in a new Julia session with your code.

**Comment by tknopp** [comment]
maybe you don't have german locale installed? try it with the Italian one

**Comment by tknopp** [comment]
should be `""it_IT"`

**Comment by giordano** [comment]
See my update message above.

**Comment by tknopp** [comment]
hm strange. I am on MacOS maybe that matters? The `Cstring(0x0000000000000000)` indicates that the locale setting has not worked.

**Comment by giordano** [comment]
Not even with `it_IT.UTF-8` (which at least return a non-null string):

```julia
julia> ccall((:setlocale, "libc"), Cstring,(Cint, Cstring), 0, "it_IT.UTF-8")
Cstring(0x0000557cbd189d70)

julia> big(1.0)
1.000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by tknopp** [comment]
try `unsafe_string(ccall((:setlocale,"libc"), Cstring,(Cint,Cstring),0,"it_IT.UTF-8" ))`
would be interesting whats the return value.

**Comment by giordano** [comment]
```julia
julia> unsafe_string(ccall((:setlocale,"libc"), Cstring,(Cint,Cstring),0,"it_IT.UTF-8" ))
"it_IT.UTF-8"
```

**Comment by tknopp** [comment]
strange.

**Comment by yuyichao** [comment]
what's your `locale -a`?

**Comment by giordano** [comment]
```
$ locale -a
C
C.UTF-8
it_IT.utf8
POSIX
```

**Comment by yuyichao** [comment]
Sorry should be `locale` (updated above). And what's `env | grep 'LC_\|LANG'`

**Comment by tknopp** [comment]
@yuyichao could you check if my reduced case above raises the issue for you?

**Comment by yuyichao** [comment]
And maybe try `ccall((:setlocale,"libc"), Cstring,(Cint,Cstring), 1,"it_IT.UTF-8" ))` Or maybe replace the `1` with the actual definition of `LC_NUMERIC` on your setup.

**Comment by giordano** [comment]
```
$ locale
LANG=it_IT.UTF-8
LANGUAGE=
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=
$ env | grep 'LC_\|LANG'
LANG=it_IT.UTF-8
LANGUAGE=
```

Note that in any case the issue affects parsing as well:
```julia
julia> using Gtk

julia> big"1,0"
1,000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> big"1.0"
1,000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by giordano** [comment]
@yuyichao works with 1 as category argument, thanks.

**Comment by tknopp** [comment]
yea I did not know what `LC_ALL` is as an integer and therefore tried `0`

**Comment by yuyichao** [comment]
On Linux 0 is LC_CTYPE, LC_NUMERIC is 1, LC_ALL is 6.
_ALL and _NUMERIC seems to be 0 and 4 on mac.

**Comment by giordano** [comment]
Yes, I'm running Debian.

**Comment by giordano** [comment]
Issue opened at https://github.com/JuliaLang/julia/issues/21494
