### ISSUE TITLE
Incorrect Gtk.GConstants.GDK_KEY mapping for 'o' and 'O'

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGraphics/Gtk.jl#319]
While working on creating my own easier-to-remember key bindings for Gtk, I came across what I believe is a small error in the generated values for the keys 'o' and 'O' in gconsts3. As seen [here](https://github.com/JuliaGraphics/Gtk.jl/blob/master/gen/gconsts3#L3043) and [here](https://github.com/JuliaGraphics/Gtk.jl/blob/master/gen/gconsts3#L3076), these two values do not match with the rest of their alphabetical brethren. I confirmed that the values that these indicate are different from what Gtk returns upon pressing these keys. Specifically, GDK_KEY_O should be 0x004f and GDK_KEY_o should be 0x006f.

**Comment by vtjnash** [comment]
This content is autogenerated (from https://github.com/JuliaGraphics/Gtk.jl/blob/master/gen/gtk_consts_gen.jl#L74), and it looks like it's missing every trailing `f`, if you would like to make a PR to fix this, run the https://github.com/JuliaGraphics/Gtk.jl/blob/master/gen/gtk_auto_gen.jl script to rebuild this file.

**Comment by jpsamaroo** [comment]
I'd be happy to submit a PR. I should note that it seems that the autogen code hasn't been updated for Julia 0.6 yet (there are still some calls to `symbol` instead of `Symbol`, for example), so I'll probably include those fixes in the PR as well. I've never submitted a PR before, so please bear with me :smile:
