### ISSUE TITLE
Unable to use index_from_iter, because it parses string to integer in the wrong (old) way

### ISSUE THREAD

**Issue by tibaes** [JuliaGraphics/Gtk.jl#337]
Using index_from_iter throws:
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Int64

https://github.com/JuliaGraphics/Gtk.jl/blob/4e80acb8256b33858b6db90e7aa9fa76059ab32b/src/lists.jl#L127

Now Julia imposes the parse function, as:
`index_from_iter(store::GtkListStore, iter::TRI) = parse(Int, get_string_from_iter(GtkTreeModel(store), iter)) + 1`

**Comment by tknopp** [comment]
What does `Now` mean? Which Julia version are you using?

**Comment by fcard** [comment]
I don't remember `Int(::String)` ever working; `parse` has always been a requirement.

**Comment by tibaes** [comment]
@tknopp I am using Julia 0.6.1.

@fcard I am new to Julia, but I believe you are right.

**Comment by tknopp** [comment]
yea seems pretty wrong. Do you want to fix this @tibaes? Reporting an issue is in general very good (thanks!). However, Gtk.jl unfortunately has close to zero developers right now, which means that the issue will unfortunately not get automatically fixed ;-)

**Comment by tibaes** [comment]
@tknopp shure! Tomorrow I'll put a pull request to fix this :smile:
