### ISSUE TITLE
Windows vs Ubuntu: Gtk looks

### ISSUE THREAD

**Issue by loicspace** [JuliaGraphics/Gtk.jl#340]
Hi,

This is probably not an issue with Gtk.jl itself as much as one related to OS/library/gtk fun things.
The same GUI ran on Windows 10 looks more "modern":
![gtkwin](https://user-images.githubusercontent.com/17835401/33846934-b811a69c-de5d-11e7-8466-c94d628c467b.png)

-- arguably better than on Ubuntu:
![gtkubuntu](https://user-images.githubusercontent.com/17835401/33846956-cdd30f66-de5d-11e7-99e5-9d8964e9a966.png)

Both with julia 0.6.1 but I have tried across an array of Julia versions, gtk.jl versions, including master. What am I missing? I have gtk2 and 3 installed on my Ubuntu machine,
```
loic@loic-astro:~/Tools/astrogui$ dpkg -s libgtk-3-0|grep '^Version'
Version: 3.20.8-1ubuntu0~ppa1
loic@loic-astro:~/Tools/astrogui$ dpkg -s libgtk2.0-0|grep '^Version'
Version: 2.24.30-4ubuntu1~ubuntu16.04.1
```

Is it just a different "theme"?
Thanks,
Loic

**Comment by tknopp** [comment]
yes this is theming related. Ubuntu does not seem to use the standard Gtk theme. This is the standard Gtk theme:

https://blogs.gnome.org/mclasen/files/2014/06/adwaita.png

it is called adwaita.

**Comment by loicspace** [comment]
Oh I see. Switching to adwaita does yield a similar result as in Windows. I tried to mess around with gtk2+ and gtk3+ a lot to no avail when the fix was stupidly simple...Apologies and thanks for the info!
