### ISSUE TITLE
Segfaults when trying to update a GtkListView

### ISSUE THREAD

**Issue by Cruor** [JuliaGraphics/Gtk.jl#348]
Having some problems with clearing my listviews, I have attempted to debug this and the only thing I can see as a problem is that I am unable to reset the selection on the list, causing it to segfault when that row is deleted. I have tried to unselect it as show below (which also segfaults) and i have attempted too disconnect the signal as well (not shown below, but take my word for it).
I'm not experienced with Gtk so this might be my problem, but after excessive debugging I don't believe this is the case. If there is any obvious problems with this code please point them out for me, beware that the code is slightly modified to be easier to pinpoint the error.

Here is a "minimal" code example that causes the problem, the `updateTreeView` is the problematic function. 
The program will segfault when one of the rows are selected, due to all of them being cleared out for the new data.

```julia 
using Gtk, Gtk.ShortNames

function updateTreeView!(store::Gtk.GtkListStore, selection::Gtk.GtkTreeSelection, data::Array{T, 1}) where T <: Tuple
    if hasselection(selection)
        # Both of these segfaults the program
        #unselect!(selection, selected(selection))
        #unselectall!(selection)
    end

    # Segfaults because a selection is in use
    empty!(store)

    for d in data
        push!(store, d)
    end
end

# Helper function to tree list, no problems here
function generateTreeView(header::Tuple, data::Array{T, 1}) where T <: Tuple
    tupleTypes = eltype(data).parameters
    store = GtkListStore(tupleTypes...)

    for d in data
        push!(store, d)
    end

    treeView = GtkTreeView(GtkTreeModel(store))

    cols = GtkTreeViewColumn[]

    for c in 1:length(tupleTypes)
        col = GtkTreeViewColumn(
            header[c],
            GtkCellRendererText(),
            Dict([("text", c - 1)])
        )

        push!(cols, col)
    end

    push!(treeView, cols...)

    return store, treeView
end

window = Window() |> (Frame() |> (box = Box(:v)))
store, tree = generateTreeView(("Foo", "Bar", "Baz"), [(1, 2, 3), (4, 5, 6), (7, 8, 9)])
push!(box, tree)

selection = GAccessor.selection(tree)

signal_connect(selection, "changed") do widget
    updateTreeView!(store, selection, [(3, 4, 5), (2, 3, 1), (2, 4, 3)])
end

showall(window)

readline()

**Comment by Cruor** [comment]
Problem was solved by using `GLib.@sigatom` macro on the `updateTreeView!` call.

**Comment by Kelvyn88** [comment]
Thanks!!
