### ISSUE TITLE
Cannot run the Getting Started examples on bash

### ISSUE THREAD

**Issue by justapoise** [JuliaGraphics/Gtk.jl#356]
I put the examples on a win.jl and run the script on bash by `julia win.jl` but a window does not show up.
A method that works is by running it in the repl using include("win.jl").

**Comment by tknopp** [comment]
This is expected. You need to do: 

http://juliagraphics.github.io/Gtk.jl/latest/manual/nonreplusage.html

**Comment by justapoise** [comment]
I should have scrolled down the docs page. Classic rtfm. Solved.
