### ISSUE TITLE
Travis CI Broken: libgtk-3 in Julia v0.7

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGraphics/Gtk.jl#360]
You are probably aware, but I figured I would open an issue.

The problem propagates to my own module (InspectDR).

I am not certain where to look.  I don't have a good feel for how to get TravisCI to do what I want.

If you can give me a starting point (maybe a working example), I might be able to come up with a fix.

I don't really understand what changed in the migration to Julia 0.7 wrt TravisCI, though.

**Comment by tknopp** [comment]
Can you pass me a link at you travis run which fails and a link at your travis script?

**Comment by tknopp** [comment]
This actually was working:
https://github.com/JuliaGraphics/Winston.jl/blob/master/.travis.yml
see
https://travis-ci.org/JuliaGraphics/Winston.jl/builds/414953358

**Comment by ma-laforge** [comment]
Perfect I will take a look at it.

Here is mine:
https://github.com/ma-laforge/InspectDR.jl/blob/master/.travis.yml

Something tells me I will be able to figure something out using Winston, though.

**Comment by ma-laforge** [comment]
Got it working.  Thanks for the help.

Also: I personally only needed to add the `libgtk-3-dev` "addon".  The other two were not necessary.

**Comment by tknopp** [comment]
great.
