### ISSUE TITLE
issue: "using Gtk" : could not load library "libgobject-2.0"

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaGraphics/Gtk.jl#363]
- Background
`Julia` Version 0.7.0 64bit 
`Gtk` v0.16.1
win10 64bit

- Issue when `using Gtk`
![image](https://user-images.githubusercontent.com/18593116/44179584-70acec00-a0ac-11e8-955b-760e1b60d202.png)

I've seen [https://github.com/JuliaImages/ImageView.jl/issues/146](https://github.com/JuliaImages/ImageView.jl/issues/146) but I'm already using Julia from terminal outside the IDE.

**Comment by zhaotianjing** [comment]
![image](https://user-images.githubusercontent.com/18593116/44180255-3f361f80-a0b0-11e8-838d-1f72176bfe3e.png)
Same on Mac

**Comment by zhaotianjing** [comment]
I figured it out.
The problem is about the package "LibCURL"
When we use Julia as user, instead of Admin, this package has bug, cannot build successful. BTW I'm win10.
So I login as Admin, and solve the problem.
I've reported the issue, I believe this bug will be fixed by "LibCURL" soon.  :)

**Comment by tknopp** [comment]
thanks for investigating

**Comment by bjce** [comment]
Hello

I posted a [similar problem](https://github.com/JuliaImages/ImageView.jl/issues/146) about a year ago . I just installed the freshest Julia Pro version (1.1.1.1) but the problem unfortunately persists. Do you have any Idea how the problem could be solved?

**Comment by arinrb** [comment]
> Hello
> 
> I posted a [similar problem](https://github.com/JuliaImages/ImageView.jl/issues/146) about a year ago . I just installed the freshest Julia Pro version (1.1.1.1) but the problem unfortunately persists. Do you have any Idea how the problem could be solved?

Ditto

**Comment by rtdietrich** [comment]
I have the same Problem under Win10. Login as Administrator does not help.

Any Idea?

julia> using Gtk
[ Info: Precompiling Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]
ERROR: LoadError: LoadError: error compiling top-level scope: could not load library "libgobject-2.0-0"
The specified module could not be found.

**Comment by tknopp** [comment]
Maybe build again, i.e. go to Pkg mode: `] build Gtk`. The point is that the download it done at build time not precompile time.

**Comment by rtdietrich** [comment]
yes

**Comment by rtdietrich** [comment]
Switching from 1.3 to Julia 1.2 feels like a miracle. All my Problems are gone.

Thank you so much for your hint!!!!
