### ISSUE TITLE
Failed to precompile Gtk.

### ISSUE THREAD

**Issue by ghost** [JuliaGraphics/Gtk.jl#365]
I am using:
Windows 10.0.17134
Julia 1.0.0
I am unsure about the version of Gtk because `Pkg.installed()` is broken, but I just installed it today.
The installing is successful with no errors, but when trying to use the Library **in Juno and terminal** I got the following errors.

> LoadError: Failed to precompile Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44] to C:\Users\jerry\.julia\compiled\v1.0\Gtk\Vjnq0.ji.
in expression starting at C:\Users\jerry\Documents\Julia\main.jl:1
error(::String) at error.jl:33
macro expansion at logging.jl:313 [inlined]
compilecache(::Base.PkgId, ::String) at loading.jl:1184
macro expansion at logging.jl:311 [inlined]
_require(::Base.PkgId) at loading.jl:941
require(::Base.PkgId) at loading.jl:852
macro expansion at logging.jl:311 [inlined]
require(::Module, ::Symbol) at loading.jl:834
include_string(::Module, ::String, ::String) at loading.jl:1002
(::getfield(Atom, Symbol("##120#124")){String,String,Module})() at eval.jl:117
withpath(::getfield(Atom, Symbol("##120#124")){String,String,Module}, ::String) at utils.jl:30
withpath at eval.jl:46 [inlined]
#119 at eval.jl:114 [inlined]
hideprompt(::getfield(Atom, Symbol("##119#123")){String,String,Module}) at repl.jl:76
macro expansion at eval.jl:113 [inlined]
(::getfield(Atom, Symbol("##118#122")){Dict{String,Any}})() at task.jl:85

I also tried `Pkg.build("Gtk")` **in terminal** but ended up with the following errors:
> Building LibCURL ─→ `C:\Users\jerry\.julia\packages\LibCURL\Qs5og\deps\build.log`
  Building WinRPM ──→ `C:\Users\jerry\.julia\packages\WinRPM\rDDZz\deps\build.log`
┌ Error: Error building `WinRPM`:
│ ERROR: LoadError: LoadError: UndefVarError: Void not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\lX_common_h.jl:10
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1038
│  [4] include at .\sysimg.jl:29 [inlined]
│  [5] include(::String) at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\LibExpat.jl:3
│  [6] top-level scope at none:0
│  [7] include at .\boot.jl:317 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1038
│  [9] include(::Module, ::String) at .\sysimg.jl:29
│  [10] top-level scope at none:2
│  [11] eval at .\boot.jl:319 [inlined]
│  [12] eval(::Expr) at .\client.jl:389
│  [13] top-level scope at .\none:3
│ in expression starting at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\lX_common_h.jl:18
│ in expression starting at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\LibExpat.jl:16
│ ERROR: LoadError: Failed to precompile LibExpat [522f3ed2-3f36-55e3-b6df-e94fee9b0c07] to C:\Users\jerry\.julia\compiled\v1.0\LibExpat\MYp8o.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1184
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] top-level scope at none:2
│  [12] eval at .\boot.jl:319 [inlined]
│  [13] eval(::Expr) at .\client.jl:389
│  [14] top-level scope at .\none:3
│ in expression starting at C:\Users\jerry\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:12
│ ERROR: LoadError: Failed to precompile WinRPM [c17dfb99-b4f7-5aad-8812-456da1ad7187] to C:\Users\jerry\.julia\compiled\v1.0\WinRPM\ko3j0.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1184
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] top-level scope at C:\Users\jerry\.julia\packages\WinRPM\rDDZz\deps\build.jl:2
│  [9] include at .\boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:388
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\jerry\.julia\packages\WinRPM\rDDZz\deps\build.jl:1
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068
  Building Homebrew → `C:\Users\jerry\.julia\packages\Homebrew\l8kUw\deps\build.log`
  Building Cairo ───→ `C:\Users\jerry\.julia\packages\Cairo\blE1h\deps\build.log`
┌ Error: Error building `Cairo`:
│ ERROR: LoadError: LoadError: UndefVarError: Void not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\lX_common_h.jl:10
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1038
│  [4] include at .\sysimg.jl:29 [inlined]
│  [5] include(::String) at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\LibExpat.jl:3
│  [6] top-level scope at none:0
│  [7] include at .\boot.jl:317 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1038
│  [9] include(::Module, ::String) at .\sysimg.jl:29
│  [10] top-level scope at none:2
│  [11] eval at .\boot.jl:319 [inlined]
│  [12] eval(::Expr) at .\client.jl:389
│  [13] top-level scope at .\none:3
│ in expression starting at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\lX_common_h.jl:18
│ in expression starting at C:\Users\jerry\.julia\packages\LibExpat\FAade\src\LibExpat.jl:16
│ ERROR: LoadError: Failed to precompile LibExpat [522f3ed2-3f36-55e3-b6df-e94fee9b0c07] to C:\Users\jerry\.julia\compiled\v1.0\LibExpat\MYp8o.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1184
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] top-level scope at none:2
│  [12] eval at .\boot.jl:319 [inlined]
│  [13] eval(::Expr) at .\client.jl:389
│  [14] top-level scope at .\none:3
│ in expression starting at C:\Users\jerry\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:12
│ ERROR: LoadError: Failed to precompile WinRPM [c17dfb99-b4f7-5aad-8812-456da1ad7187] to C:\Users\jerry\.julia\compiled\v1.0\WinRPM\ko3j0.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1184
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] top-level scope at C:\Users\jerry\.julia\packages\Cairo\blE1h\deps\build.jl:33
│  [9] include at .\boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:388
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\jerry\.julia\packages\Cairo\blE1h\deps\build.jl:32
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068
  Building Gtk ─────→ `C:\Users\jerry\.julia\packages\Gtk\oHM1K\deps\build.log`
┌ Error: Error building `Gtk`:
│ ERROR: LoadError: syntax: misplaced assignment statement in "[glib = library_dependency("glib", aliases = ["libglib-2.0", "libglib-2.0-0"], group = group); gobject = library_dependency("gobject", aliases = ["libgobject-2.0", "libgobject-2.0-0"], group = group); gtk = library_dependency("gtk", aliases = ["libgtk-3", "libgtk-3-0"], group = group); gdk = library_dependency("gdk", aliases = ["libgdk-3", "libgdk-3-0"], group = group); gdk_pixbuf = library_dependency("gdk_pixbuf", aliases = ["libgdk_pixbuf-2.0", "libgdk_pixbuf-2.0-0"], group = group); gio = library_dependency("gio", aliases = ["libgio-2.0", "libgio-2.0-0"], group = group)]"
│ Stacktrace:
│  [1] include at .\boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at .\loading.jl:1038
│  [3] include(::Module, ::String) at .\sysimg.jl:29
│  [4] include(::String) at .\client.jl:388
│  [5] top-level scope at none:0
│ in expression starting at C:\Users\jerry\.julia\packages\Gtk\oHM1K\deps\build.jl:7
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068

This is my first time opening an issue on GitHub, I apologize for any mistakes that I made.
Thanks.

**Comment by tknopp** [comment]
This is expected. WinRPM is not ported to 1.0 yet. Please just use Julia 0.7 and it will work

**Comment by Vexatos** [comment]
The bottom error is still occuring on the latest version of WinRPM which supports Julia 1.0.
```
  Building Gtk ─────→ `~/.julia/packages/Gtk/oHM1K/deps/build.log`
┌ Error: Error building `Gtk`:
│ ERROR: LoadError: syntax: misplaced assignment statement in "[glib = library_dependency("glib", aliases = ["libglib-2.0", "libglib-2.0-0"], group = group); gobject = library_dependency("gobject", aliases = ["libgobject-2.0", "libgobject-2.0-0"], group = group); gtk = library_dependency("gtk", aliases = ["libgtk-3", "libgtk-3-0"], group = group); gdk = library_dependency("gdk", aliases = ["libgdk-3", "libgdk-3-0"], group = group); gdk_pixbuf = library_dependency("gdk_pixbuf", aliases = ["libgdk_pixbuf-2.0", "libgdk_pixbuf-2.0-0"], group = group); gio = library_dependency("gio", aliases = ["libgio-2.0", "libgio-2.0-0"], group = group)]"
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1038
│  [3] include(::Module, ::String) at ./sysimg.jl:29
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│ in expression starting at /home/durian/.julia/packages/Gtk/oHM1K/deps/build.jl:7
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```
