### ISSUE TITLE
Defining gtktype outside of Gtk doesn't work anymore

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaGraphics/Gtk.jl#367]
```julia
julia> import ..Gtk: suffix, @gtktype_custom_symname,
       @gtktype_custom_symname_and_lib, @Gtype, _gtksubtype_constructors

julia> Gtk.@gtktype GtkClipboard
ERROR: UndefVarError: GtkClipboardLeaf not defined
Stacktrace:
 [1] _gtksubtype_constructors(::Symbol) at /Users/bieler/.julia/dev/Gtk/src/gtktypes.jl:4
 [2] top-level scope at /Users/bieler/.julia/dev/Gtk/src/GLib/gtype.jl:199
 [3] top-level scope at /Users/bieler/.julia/dev/Gtk/src/gtktypes.jl:18
```

I think the issue is with the new behaviour of `@__MODULE__` here, it tries to get GtkClipboardLeaf from Gtk instead of the calling module.

https://github.com/JuliaGraphics/Gtk.jl/blob/66ca486d6c15199ff027afa833653c4bf217ea24/src/gtktypes.jl#L2-L4

The solution might be to pass the calling module as an optional argument, I'll see if I can do something along these lines.

**Comment by jonathanBieler** [comment]
I looked a bit into it and I think this business of evaluating into another package is quite nasty and should be avoided. You can make it work but it might create problems with compilation later on. I see two possible solutions:

1. A set of macro/functions that allow to define types in other packages. That would basically be more verbose versions of the macros used in Gtk that doesn't rely on evaluating the actual types.

2. Put everything in Gtk.jl. As far as I know the only package that rely on this feature is GtkSourceWidget (and I'm using it) so we could just put it in Gtk.jl. I'm not a big fan of this, if someone in the future want to do binding for WebKitGTK or something else it would be a bit too much.

I'll look for into 1. for the moment.

**Comment by tknopp** [comment]
I have not fully understood the coupling between GLib module and Gtk to propose whats the best solution.

By the way, should we merge your fork of GtkSourceWidget into my original repository and I give you write access? The package is/was even in METADATA although it has never been tagged and in turn is not installable: https://github.com/JuliaLang/METADATA.jl/pull/2064

**Comment by jonathanBieler** [comment]
To explain a bit the issue (before I forget), the `@gtktype MyGtkType` macro generates code a bit like this:

```
type MyGtkType ... end

MyGtkTypeLeaf(args...) = ...
```

The issue is that to define the constructor the macro is calling into Gtk to get some properties of `MyGtkType` (e.g. is it a container ?) and to do so it needs the actual type, and not just the symbol, which is all you get in a macro. So to get the type it evals the symbol. In previous version it would eval in the external package but that doesn't work so well anymore (and is probably a bit wrong to begin with).

The solution 1. I was trying is to rewrite the macro such that it generate code like this:

```
type MyGtkType ... end

if isa(MyGtkType, GtkContainer)
    @define_container_constructor MyGtkType
end
```
which doesn't rely on evaluating from inside the macro anymore. This work fine for the constructor part, but there's other parts of `@gtktype` that aren't so easy to rewrite.

I'll explore 2. a bit more.

**Comment by vtjnash** [comment]
This code is supposed to use the variable `__module__`, not the macro (though might need to do some work to thread the variable to the right places)

**Comment by jonathanBieler** [comment]
What is this `__module__` variable, its something that was used in previous version ?

I found that you can just do that:

```
Gtk.curr_module() = @__MODULE__
Gtk.GLib.curr_module() = @__MODULE__
```

In the external module (and put them back to their default value at the end). It seems to work fine, even though it's a bit hacky.

**Comment by tknopp** [comment]
It would be great if we could find a better fix since currently one also gets a warning when `using Gtk`

**Comment by fcard** [comment]
`__module__` is an implicit argument to macros.
```julia
macro m()
  println(__module__)
end

__module__ # undefined var error

@m # will print `Main`

module M1
  Main.@m # will print `Main.M1`
end
```

You need to use it like this:
```julia
function _gtksubtype_constructors(name::Symbol, cm::Module)
    # ...
end

macro gtktype_custom_symname_and_lib(name, symname, lib)
    esc(quote
        @Gtype $name $lib $symname
        _gtksubtype_constructors($(QuoteNode(name)), $__module__)
    end)
end
```

**Comment by tknopp** [comment]
@jonathanBieler please reopen if the issue persists.
