### ISSUE TITLE
Error building `Gtk`

### ISSUE THREAD

**Issue by somi38** [JuliaGraphics/Gtk.jl#369]
got this issue running Julia v1.0.0  x64 upon win10 x64

Error: Error building `Gtk`:
│ [ Info: Multiple package candidates found for mingw64(libjpeg-8.dll), picking newest.
│ ERROR: LoadError: MethodError: no method matching length(::WinRPM.RPMVersionNumber)
│ Closest candidates are:
│   length(!Matched::Core.SimpleVector) at essentials.jl:571
│   length(!Matched::Base.MethodList) at reflection.jl:728
│   length(!Matched::Core.MethodTable) at reflection.jl:802

**Comment by tknopp** [comment]
This is an issue with `WinRPM.jl` could you report the issue their?

**Comment by somi38** [comment]
Hi tknopp,

I'm stuck on this error, not getting response from WinRPM.jl.
Can you please help, most pkgs are depending on Gtk.

**Comment by tknopp** [comment]
I can't help there since this has nothing to do with Gtk.jl and I don't have access to windows. I recommend using Julia 0.7 in which that error does not occur. It might be that WinRPM is simply not ready for 1.0 yet. There is no downside in using Julia 0.7.

**Comment by tknopp** [comment]
this has been resolved.
