### ISSUE TITLE
could not load library "libgobject-2.0"

### ISSUE THREAD

**Issue by ernstvanzyl** [JuliaGraphics/Gtk.jl#370]
I'm using Julia 1.0 on Windows 10.
I found this in the source code:
`if KERNEL == :Windows`
but my computer reports `:NT` for `Base.Sys.KERNEL`

**Comment by jonathanBieler** [comment]
Could you try to change those to 

`if any(KERNEL .== [:Windows, :NT])`

and check if it solve the issue ? I don't have a Windows 10 machine, so I can test myself.

**Comment by ernstvanzyl** [comment]
Yes that does it. Gtk will now precompile and my test app works.

**Comment by jonathanBieler** [comment]
Nice, I'll make a PR for it then (unless you want to do it of course).

**Comment by ernstvanzyl** [comment]
I'll leave that to the professionals.
