### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by zhangliye** [JuliaGraphics/Gtk.jl#378]
> julia> using Gtk
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
ERROR: InitError: Cannot open display:
Stacktrace:
 [1] Gtk.GLib.GError(::Gtk.##235#236) at /home/liye/.julia/v0.6/Gtk/src/GLib/gerror.jl:17
 [2] __init__() at /home/liye/.julia/v0.6/Gtk/src/events.jl:10
 [3] _include_from_serialized(::String) at ./loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [5] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [6] _require(::Symbol) at ./loading.jl:441
 [7] require(::Symbol) at ./loading.jl:405
during initialization of module Gtk

Version information:
> julia> versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, westmere)

**Comment by yuyichao** [comment]
I'm assuming you are using ubuntu (I didn't know they already started using mir by default). Are you running as super user or at least a different user as the one that started the graphic session?

**Comment by tknopp** [comment]
I think I have seen such a problem. It was when I logged in remotely into an ubuntu machine. In may case it was then an issue with nvidia driver. The point is: can you actually open `nautilus` or any other Gtk program?

**Comment by zhangliye** [comment]
Thanks! I remotely logged the Linux server from the Window 7 laptop, not as a super user.  This should be the problem. Thanks!

**Comment by yuyichao** [comment]
In that case it is a setup problem and not a Gtk.jl problem...... I'm not sure how/if ssh forward works for Mir.
