### ISSUE TITLE
Gtk failed to precompile: missing libgtk-3.so

### ISSUE THREAD

**Issue by William-Purvis** [JuliaGraphics/Gtk.jl#380]
I'm new to Julia, just installed 1.0.0 and pulled Gtk.jl as I want to build a GUI with it.
As soon as I typed 
  using Gtk
it started to precompile, but failed, saying it couldn't find libgtk-so.0
After checking that libgtk-3 is installed, and pondering for a day or two, I realised that
julia brings its own copies of the libraries (julia/lib/julia) and, of course, that doesn't contain
libgtk-3.so.0.

I copied the system copy into the julia directory and it started up.

It now works, up to a point. The examples/2048.jl falls flat as the Gtk functions now
seem to be prefixed by Gtk, so Window => GtkWindow.

Not so much an issue but, you could mention it in the Installation notes, which are rather
patchy.

Bill

**Comment by tknopp** [comment]
This is on linux, right? On linux it uses the system libraries, not own copies. you should not copy system libraries around. If you had an error it would be very helpful to see what it was. And what your system configuration is.

**Comment by William-Purvis** [comment]
OK, I've removed libgtk-3.so from the julia/lib directory, and typed 'using Gtk' under julia.
I got the following:
julia> using Gtk
ERROR: InitError: error compiling __init__: error compiling Type: could not load library "libgtk-3"
libgtk-3.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:627
 [2] macro expansion at ./logging.jl:312 [inlined]
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:698
 [4] _require(::Base.PkgId) at ./loading.jl:931
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
during initialization of module Gtk

restoring the link and it works OK.
Just noticed, doing the above, that I had copied the library into julia-1.0.0/lib, not
julia-1.0.0/julia as I said originally.

**Comment by tknopp** [comment]
Might it be that you had an error when you installed Gtk.jl first? In that case you first have to run
```
  Pkg.build("Gtk")
```

**Comment by William-Purvis** [comment]
Thanks,
Tried Pkg.build("Gtk")  and got Pkg not defined!
Recalled something from the first time, but had to dig in the web pages to find to use ']' to get  into
Pkg mode, then 'build Gtk' ran. Came up needing system password to install dependencies
but that doesn't work, as the prompt to install them gets aborted:

 The following additional packages will be installed:
│   libatk-bridge2.0-dev libatspi2.0-dev libepoxy-dev libgmp-dev libgmpxx4ldbl
│   libxtst-dev nettle-dev x11proto-record-dev
│ Suggested packages:
│   gmp-doc libgmp10-doc libmpfr-dev libgtk-3-doc
│ The following NEW packages will be installed
│   libatk-bridge2.0-dev libatspi2.0-dev libepoxy-dev libgmp-dev libgmpxx4ldbl
│   libgtk-3-dev libxtst-dev nettle-dev x11proto-record-dev
│ 0 to upgrade, 9 to newly install, 0 to remove and 47 not to upgrade.
│ Need to get 2355 kB of archives.
│ After this operation, 17.3 MB of additional disk space will be used.
│ Do you want to continue? [Y/n] Abort.
│ ERROR: LoadError: failed process: Process(`sudo apt-get install libgtk-3-dev`, ProcessExited(1)) [1]
Installing the required dependencies outside julia and re-ran and this time it all works OK,
Both my problems resolved.

**Comment by tknopp** [comment]
You have to do `using Pkg` in order to use Pkg. Or just use the Pkg mode.
Its a little odd that the prompt did abort. Not sure where to file an issue about that (julia itself or BinDeps?).

**Comment by emmettgb** [comment]
Wow now I feel dumb, @tknopp ...
Originally I had issues with Cairo and had to rebuild it, and I thought I was out of the Pkg build hot-water. I am on fedora, so I assumed that I was missing a dep, and promptly did:
```bash
sudo dnf install libgtk-3.so.0
```
When all along I merely needed to rebuild the package.

**Comment by tknopp** [comment]
This is an old issue that is obsolete. We now get the binaries from binary builder. Thus, it should have no effect to install system libraries
