### ISSUE TITLE
Testing packages that depend on Gtk ?

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaGraphics/Gtk.jl#388]
I'm trying to update some packages that uses Gtk but the test fails on travis because Gtk doesn't build. I've tried a couple of changes to the build script without success. Is there a trick to make it work ?

https://travis-ci.org/timholy/GtkUtilities.jl/jobs/431076734

https://travis-ci.org/jonathanBieler/GtkSourceWidget.jl/jobs/425646772

**Comment by tknopp** [comment]
Have a look at Winston, which is all green on travis:
https://github.com/JuliaGraphics/Winston.jl/blob/master/.travis.yml

You seem to need to preinstall `libgtk-3-dev` in the travis configuration.

**Comment by jonathanBieler** [comment]
Thanks that worked for GtkUtilities, I still need to do GtkSourceWidget but it should be fine.
