### ISSUE TITLE
does Gtk support text on canvas via Cairo?

### ISSUE THREAD

**Issue by geluso** [JuliaGraphics/Gtk.jl#389]
Is it possible to draw text onto a canvas? I'm able to draw lines, rectangles and change colors for basic shapes. Now I want to draw some text inside the canvas.

I'm looking at the Cairo documentation and see methods like `set_font_face` and `show_text` but those methods aren't defined like the `rectangle` and `stroke` methods are.

I'm using Gtk and Graphics. Do those libraries maybe just not support these Cairo methods?

https://valadoc.org/cairo/Cairo.Context

Some of the methods listed at that page are available, but none of the text ones I want.

```
julia> rectangle
rectangle (generic function with 3 methods)

julia> fill
fill (generic function with 6 methods)

julia> set_dash
set_dash (generic function with 3 methods)

julia> set_fill_rule
ERROR: UndefVarError: set_fill_rule not defined

julia> font_face
ERROR: UndefVarError: font_face not defined

julia> set_font_face
ERROR: UndefVarError: set_font_face not defined
```

**Comment by lobingera** [comment]
The methods you see here are exported from Gtk and Graphics -> which is a thin layer on top of https://github.com/JuliaGraphics/Cairo.jl -> which is the library adaptation. Not all functions of libcairo are available.
Cairo.jl supports 
```
Cairo.select_font_face(ctx::CairoContext,family::AbstractString,slant,weight)
Cairo.show_text(ctx::CairoContext,value::AbstractString)
```
with a pure libcairo interface and 
set_font_face, set_text and text with a small adaptation to libpango.

**Comment by geluso** [comment]
Awesome. I imported Cairo and found everything available. Thanks for clearing that up.
