### ISSUE TITLE
TreeView "row-activated" callback not working

### ISSUE THREAD

**Issue by igor-krawczuk** [JuliaGraphics/Gtk.jl#405]
Hi, I've been trying to use TreeView + the "row-activated" signal in combination with the toggle renderer to create an "selected" toggle, but my callback doesn't fire. trying a minimal example baed on mostly the code from the docs:

```
using Gtk
ls = GtkListStore(String, Int, Bool)

push!(ls,("Peter",20,false))
push!(ls,("Paul",30,false))
push!(ls,("Mary",25,true))

tv = GtkTreeView(GtkTreeModel(ls))


rTxt = GtkCellRendererText()
rTog = GtkCellRendererToggle()

c1 = GtkTreeViewColumn("Name", rTxt, Dict([("text",0)]))
c2 = GtkTreeViewColumn("Age", rTxt, Dict([("text",1)]))
c3 = GtkTreeViewColumn("Female", rTog, Dict([("active",2)]))

push!(tv, c1, c2, c3)
win = GtkWindow(tv, "List View")
showall(win)

selection = GAccessor.selection(tv)

signal_connect(tv, "row-activated") do widget 
  if hasselection(selection)
     print("logme")
    currentIt = selected(selection)

    # now you can to something with the selected item
    ls[currentIt,3]=!ls[currentIt,3]
  end
end

```

But neither does the toglge change, not does the console log "logme"), whereas if I try e.g. the selection callback from the docs, it does log. I have also tried  `do widget, path, col, udata` [following the signal docs](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#GtkTreeView-row-activated) but it doesn't seem to work that way either (don't get any errors either though).

This is on Linux,  Julia Version 1.0.1, Gtk.jl 0.16.4

**Comment by jonathanBieler** [comment]
I'm not sure what the issue is but using the explicit `signal_connect` solves the problem:

```julia

using Gtk
ls = GtkListStore(String, Int, Bool)

push!(ls,("Peter",20,false))
push!(ls,("Paul",30,false))
push!(ls,("Mary",25,true))

tv = GtkTreeView(GtkTreeModel(ls))

rTxt = GtkCellRendererText()
rTog = GtkCellRendererToggle()

c1 = GtkTreeViewColumn("Name", rTxt, Dict([("text",0)]))
c2 = GtkTreeViewColumn("Age", rTxt, Dict([("text",1)]))
c3 = GtkTreeViewColumn("Female", rTog, Dict([("active",2)]))
c3.clickable[Bool] = true

push!(tv, c1, c2, c3)

function activate_row_cb(widgetptr::Ptr, path::Ptr, column::Ptr, user_data)

    tv = convert(GtkTreeView,widgetptr)
    ls = user_data
    println("I've been double-clicked")

    selection = GAccessor.selection(tv)

    if hasselection(selection)
        currentIt = selected(selection)
        # now you can to something with the selected item
        @show ls[currentIt,3]
    end
    nothing
end

signal_connect(activate_row_cb, tv, "row-activated", Nothing, (Ptr{GtkTreePath},Ptr{GtkTreeViewColumn}), false, ls)

win = GtkWindow(tv, "List View")
showall(win)
```

The simple syntax `signal_connect(tv, "row-activated") do widget` is convenient for simple callbacks but I don't know if it can work for more complex cases like this one (the callback needs to take path and column as argument).

**Comment by igor-krawczuk** [comment]
Thanks, I saw the simple signal_connect was referred to as buggy so I thought it might be that, but it didn't state for what exactly, and since it failed silently I wasn't sure what might be the cause.
