### ISSUE TITLE
GtkWindow disappeared soon after it was opened ?

### ISSUE THREAD

**Issue by kailotus** [JuliaGraphics/Gtk.jl#410]
Hello everyone : 
I used Gtk to develop Julia's GUI application. There is a code (gtktest.jl) as follows:
~~~~~
Using Gtk
Win = GtkWindow("Julia+Gtk")
Vbox = GtkBox(:v)
Push!(win, vbox)
Cancel = GtkButton("Cancel")
Ok = GtkButton("OK")
Push!(vbox, ok)
Push!(vbox, cancel)
Showall(win)
~~~~~
When I use Julia REPL to execute:
Julia> include("gtktest.jl")
The Gtk window can be displayed normally.
![gtktest](https://user-images.githubusercontent.com/7297066/55270904-d23e6580-52df-11e9-8bbe-e525f543d8d9.png)

But when I use the Microsoft Windows command prompt character and give the command:
C:\Temp>julia gtktest.jl
I found that the window flickered and disappeared. Has anyone ever had such a situation?
By the way, please ask how to solve this problem?
Thank you all.

**Comment by jonathanBieler** [comment]
See : http://juliagraphics.github.io/Gtk.jl/latest/manual/nonreplusage.html

**Comment by tknopp** [comment]
This is an artifact since we call the mainloop in non-blocking way in a task. I think this is very handy feature.

**Comment by kailotus** [comment]
I have solved this problem, thank you very much.
