### ISSUE TITLE
How to clear an image in GtkImage

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#412]
I trying to clear the image on a GtkImage

**Comment by jonathanBieler** [comment]
Looks like `empty!` should do it:

https://github.com/JuliaGraphics/Gtk.jl/blob/1cf873893d0fa8a0abfcf0b7dd487690b942fb82/src/displays.jl#L283

Sometimes searching directly in the source here, or on the Gtk docs (then you can search for `gtk_image_clear` here) is the easiest way to find something.

**Comment by Kelvyn88** [comment]
Thanks! I have a problem.

I use Plots and pyplot() to plot some data and save the figure as .png. Then I set_gtk_property!(gtkimg, :file, filename).

Until here everything works fine. But when I clear the GtkImage() with empty and set another file name, it save the last plot and the new one.

**Comment by jonathanBieler** [comment]
Maybe you need to use `gtk_image_set_from_file`, I'm not sure.

You can find it here:

https://github.com/JuliaGraphics/Gtk.jl/blob/fe6739a3a345ba804030c8d379daa15f30055903/gen/gbox3#L1972

And use it with `GAccessor.from_file`.
