### ISSUE TITLE
Unable to render when a window has been closed.

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaGraphics/Gtk.jl#413]
Hello, I'm working on a script that can render, and to some extent, animate a cart pole, when given the position of the cart pole and the angle the pole makes with the normal. The script works fine when run and re-run in REPL mode. The script is a prototype for a function (calling it `render`) that will be used in primarily in REPL but can also be used in a program by calling the function. Any and all rendering is handled by the `render` function, which accepts a state and the Canvas. Now, when the script has run its course, and if the window is still visible, render can be called any amount of times, and the updates can be seen in the created window. 

However, when the window is closed, and then reopened using `visible(win, true)`, I get a blank window, but the render function doesn't work with it. The window stays blank. 

Ideally, I'd like for the window to open when the script is run, render the state as many times as `render()` is called, and if the window has been closed, just call `visible(win, true)` and call `render()` again see the painted scene in the window. How do I achieve that? [Here is the script for reference.](https://gist.github.com/kraftpunk97/a62fb791b58c1cc995c766d1f5b63dc6)

Thanks.

**Comment by vtjnash** [comment]
Odd, that seems to suggest the notify_realize/notify_unrealized handlers are not firing, or perhaps that it was configured to destroy the window when it was closed.

**Comment by kraftpunk97** [comment]
@vtjnash I forgot to mention it in the post, but I'm sometimes getting these `Gtk-Critical **: gtk_widget_show assertion GTK_IS_WIDGET(WIDGET)` messages, after I've closed the wi dow and called render after reopening it via visible...

**Comment by kraftpunk97** [comment]
@vtjnash After a little more experimentation, I realised that the problem occurs only when the window is closed by. clicking on the close button. If I close the window by executing `visible(win, false)` and then reopen using `visible(win, true)`, not only does render() work as intended, but the window opens with the last state already drawn. This is the case when closing by the close button; the window would reopen after `visible(win, true)`, but it would be completely blank.

**Comment by kraftpunk97** [comment]
[I also found this StackOverflow article, which describes a problem similar to min,](https://stackoverflow.com/questions/40736476/reopen-window-throws-gtk-critical-gtk-widget-get-window-assertion-gtk-is-w) but is for python.

**Comment by jonathanBieler** [comment]
I think the problem is that when you close you window the child widget gets [unrealized](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-unrealize), so your canvas gets broken. If you re-initialise everything then it works:

```julia
c = @GtkCanvas()
win = GtkWindow(c, "CartPole", 600, 400)
set_gtk_property!(win, :resizable, false)
showall(win)
```

**Comment by vtjnash** [comment]
Docs: https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-hide-on-delete

**Comment by kraftpunk97** [comment]
@vtjnash How do I access that function in Julia?

**Comment by kraftpunk97** [comment]
@vtjnash Okay, so I have made changes to the original script ([relinking here for your convenience](https://gist.github.com/kraftpunk97/a62fb791b58c1cc995c766d1f5b63dc6)). Specifically, I added `ccall((:gtk_widget_hide_on_delete, Gtk.libgtk), Bool, (Ptr{GObject}, ), win)` after declaring and initialising `win`. However, the end result is still the same. I forgot to mention it in my original post, but if it helps, I get this warning 
```
(process:3217): Gtk-WARNING **: 17:03:38.542: Locale not supported by C library.
    Using the fallback 'C' locale.
```

every time I import Gtk. Are the two related?

**Comment by Kelvyn88** [comment]
any news here?

**Comment by kraftpunk97** [comment]
@Kelvyn88 Yeah I actually solved my problem. Had to use a hide_on_delete callback. This example should help...

```
signal_connect(win, "delete-event") do widget, event ccall((:gtk_widget_hide_on_delete, Gtk.libgtk), Bool, (Ptr{GObject},), win) end
```

Here's a working example, if you need a [reference](https://github.com/kraftpunk97/Gym.jl/blob/5db98929a44203ea15e351e8eb645e6ca3481161/src/Envs/classic_control/vis/acrobot.jl#L21)

**Comment by kraftpunk97** [comment]
Closing this issue...
