### ISSUE TITLE
Configuring .travis.yml for a package that imports Gtk.jl

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaGraphics/Gtk.jl#418]
Hello. I'm working on a [package](https://github.com/kraftpunk97/Gym.jl/tree/CI) that imports Gtk.jl and I'm trying to set up CI for this package. However, I haven't used travis (or any other CI tools, for that matter) before, and my current configuration file gets this error
``` 
LoadError: LoadError: LoadError: LoadError: LoadError: InitError: Cannot open display: 
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] Gtk.GLib.GError(::getfield(Gtk, Symbol("##233#234"))) at /home/travis/.julia/packages/Gtk/aP55V/src/GLib/gerror.jl:17
```

How should I modify my .travis.yml to overcome this error?

**Comment by lobingera** [comment]
Take a look at Gtk.jl's own .travis.yml. To run gtk on headless systems Xvb and similar is needed.

**Comment by kraftpunk97** [comment]
@lobingera Thanks. That worked. For a package that's not really very big, it sure took a lot of time (~5 mins)to load. I also came across this warning...

```
** (julia:6598): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
** (julia:6595): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```

I also discovered this warning in Gtk.jl's Job log. Is the warning related to the long job times?
