### ISSUE TITLE
Gtk Getting Started example not working on Julia v1.0.3 or 1.1.1 on MacOS

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaGraphics/Gtk.jl#421]
I run the code from this example: https://juliagraphics.github.io/Gtk.jl/latest/manual/gettingStarted.html#Getting-Started-1

No button shows up on 1.0.3 or 1.1.1....

**Comment by jonathanBieler** [comment]
Strange, what do you get ? and empty window ? Note that the button takes the whole window.

**Comment by timholy** [comment]
#414?

**Comment by logankilpatrick** [comment]
@jonathanBieler yes, just a blank window. And I am also on MacOS Mohave @timholy I read through #414 and it didn’t look like anything got resolved.

**Comment by mgalenb** [comment]
+1 i also have this issue. also waiting for [#414](https://github.com/JuliaGraphics/Gtk.jl/issues/414) to be resolved.

**Comment by logankilpatrick** [comment]
@tknopp anything I can do to help out on the resolution for this?

**Comment by tknopp** [comment]
I don't know. This is not really a Gtk.jl bug but an issue with the Homebrew.jl installation (since it works here for me). We could check versions, I have:
```
julia> Homebrew.list()
29-element Array{Homebrew.BrewPkg,1}:
 atk: 2.32.0                      
 cairo: 1.16.0                    
 fontconfig: 2.13.1               
 freetype: 2.10.0                 
 fribidi: 1.0.5                   
 gdbm: 1.18.1                     
 gdk-pixbuf: 2.38.1               
 gettext: 0.19.8.1                
 glib: 2.60.1                     
 graphite2: 1.3.13                
 gsettings-desktop-schemas: 3.32.0
 gtk+3: 3.24.8                    
 harfbuzz: 2.4.0_1                
 hicolor-icon-theme: 0.17         
 icu4c: 64.2                      
 jpeg: 9c                         
 libcroco: 0.6.13                 
 libepoxy: 1.5.3                  
 libffi: 3.2.1                    
 libpng: 1.6.37                   
 librsvg: 2.44.13                 
 libtiff: 4.0.10_1                
 pango: 1.42.4_1                  
 pcre: 8.43                       
 pixman: 0.38.4                   
 pkg-config: 0.29.2               
 readline: 8.0.0                  
 sqlite: 3.28.0                   
 xz: 5.2.4 
```
If yours are more recent then that's the issue.

**Comment by logankilpatrick** [comment]
How do I add HomeBrew like you're using? I did `add HomeBrew` and got an error.  I also got an error when I did `Homebrew.list()`  (I am not familiar with HomeBrew )

**Comment by tknopp** [comment]
`add Homebrew` and `using Homebrew`

**Comment by mgalenb** [comment]
i checked and the only difference in version is  glib: 2.60.1 (yours)  glib: 2.60.2 (mine). 
```
julia> Homebrew.list()
31-element Array{Homebrew.BrewPkg,1}:
 adwaita-icon-theme: 3.32.0       
 atk: 2.32.0                      
 cairo: 1.16.0                    
 fontconfig: 2.13.1               
 freetype: 2.10.0                 
 fribidi: 1.0.5                   
 gdbm: 1.18.1                     
 gdk-pixbuf: 2.38.1               
 gettext: 0.19.8.1                
 glib: 2.60.2                     
 graphite2: 1.3.13                
 gsettings-desktop-schemas: 3.32.0
 gtk+3: 3.24.8                    
 harfbuzz: 2.4.0_1                
 hicolor-icon-theme: 0.17         
 icu4c: 64.2                      
 jpeg: 9c                         
 libcroco: 0.6.13                 
 libepoxy: 1.5.3                  
 libffi: 3.2.1                    
 libpng: 1.6.37                   
 librsvg: 2.44.14                 
 libtiff: 4.0.10_1                
 openssl: 1.0.2r                  
 pango: 1.42.4_1                  
 pcre: 8.43                       
 pixman: 0.38.4                   
 python: 3.7.3                    
 readline: 8.0.0_1                
 sqlite: 3.28.0                   
 xz: 5.2.4   
```

**Comment by logankilpatrick** [comment]
Mine is `Homebrew.BrewPkg[adwaita-icon-theme: 3.32.0, 
atk: 2.32.0, 
cairo: 1.16.0, 
fontconfig: 2.13.1, 
freetype: 2.10.0, 
fribidi: 1.0.5, 
gdbm: 1.18.1, 
gdk-pixbuf: 2.38.1, 
gettext: 0.19.8.1, 
glib: 2.60.3, 
graphite2: 1.3.13, 
gsettings-desktop-schemas: 3.32.0, 
gtk+3: 3.24.8, 
harfbuzz: 2.5.1, 
hicolor-icon-theme: 0.17, 
icu4c: 64.2, 
jpeg: 9c,
 libcroco: 0.6.13,
 libepoxy: 1.5.3, 
libffi: 3.2.1, 
libpng: 1.6.37,
 librsvg: 2.44.14, 
libtiff: 4.0.10_1, 
openssl: 1.0.2r, 
pango: 1.42.4_1, 
pcre: 8.43, 
pixman: 0.38.4, 
python: 3.7.3, 
readline: 8.0.0_1, 
sqlite: 3.28.0, 
xz: 5.2.4]
julia> `

**Comment by logankilpatrick** [comment]
Also on a different version of glib....

**Comment by logankilpatrick** [comment]
How does one downgrade those versions in homebrew?

**Comment by logankilpatrick** [comment]
@staticfloat As a maintainer/core dev of Homebrew.jl, do you have any advice for the people unable to use Gtk.jl because of the difference in Homebrew package versions? Can I pin versions to match  @tknopp 's versions?

**Comment by jonathanBieler** [comment]
@logankilpatrick To downgrade packages, maybe have a look at this:

https://stackoverflow.com/a/9832084

You can run homebrew commands using:

```julia
    Homebrew.brew(`cmd`)
```

Not sure if that works though.

**Comment by fipelle** [comment]
I am having the same issue. Have you found a working solution?

**Comment by logankilpatrick** [comment]
@fipelle I am going to try downgrading this weekend and will report back.

**Comment by logankilpatrick** [comment]
On Julia 1.3 on MacOs with master, I am now able to get this example to work.
