### ISSUE TITLE
Delete GtkEntry text on clic.  

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#430]
Hi,

I´m trying to delete the label of a GtkEntry when the user click on it. Gtkentry hasn't "clicked" signal connect.

**Comment by jonathanBieler** [comment]
You could try the “focus-in-event”`signal:

https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-focus-in-event

**Comment by Kelvyn88** [comment]
It doesn't work. 

Thanks for the suggestion.

**Comment by jonathanBieler** [comment]
Have you seen this part ?

>To receive this signal, the GdkWindow associated to the widget needs to enable the GDK_FOCUS_CHANGE_MASK mask.

https://github.com/JuliaGraphics/Gtk.jl/blob/fe6739a3a345ba804030c8d379daa15f30055903/gen/gbox3#L364

https://github.com/JuliaGraphics/Gtk.jl/blob/4e110ac111da3631c858886d097ef13aa0064c3d/gen/gconsts3#L1447

**Comment by Kelvyn88** [comment]
Thanks. Could you provide examples??

**Comment by jonathanBieler** [comment]
@Kelvyn88 Here you go:

```julia
using Gtk

entry = GtkEntry()
entry.text[String] = "test"

@guarded (Cint(false)) function entry_focus_in_cb(widgetptr::Ptr, eventptr::Ptr, user_data)
    entry = convert(GtkEntry, widgetptr)
    entry.text[String] = ""

    return Cint(false)
end

signal_connect(entry_focus_in_cb, entry, "focus-in-event", Cint, (Ptr{Gtk.GdkEvent},), false)

w = GtkWindow()
Gtk.GAccessor.events(w, Gtk.GConstants.GdkEventMask.FOCUS_CHANGE)

push!(w,entry)

showall(w)
```

**Comment by jonathanBieler** [comment]
@Kelvyn88 Does that solves your problem ?

**Comment by Kelvyn88** [comment]
@jonathanBieler thank you! It exactly what I need!

Kelvyn
