### ISSUE TITLE
Canvas & Plot bug

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#434]
Hi. 

I'm writing a GUI program with GTK. To show a plot created with GR, I decided to use canvas, as the example provided here: https://github.com/jheinen/GR.jl/blob/master/examples/gtk_ex.jl

When I run the code to create the canvas and show the plot everything runs correct. But, I need to clear the plot attached to the canvas and later attach a different plot. The problem is, the first time I run the code, the plot is showed, but If I do a `visible(canvas, false)` and then `visible(canvas, true)` the plot doesn't appears. 

I tried with `destroy(canvas)` and create a new with the same name and push! to a the same grid as the previous one. But it didn't work. 

With some modifications, my code is as follow (is a part of a more complex Gtk elements). 

```
    parEstPlot = Button("Plot")
    canvas = Canvas(540, 440)
    signal_connect(parEstPlot, :clicked) do widget
        global plotStatus
        function plot(ctx, w, h)
            ENV["GKS_WSTYPE"] = "142"
            ENV["GKSconid"] = @sprintf("%lu", UInt64(ctx.ptr))
            global plt = gcf()
            plt[:size] = (w, h)
            GR.plot(1:20)
        end

        function draw(widget)
            ctx = Gtk.getgc(widget)
            w = Gtk.width(widget)
            h = Gtk.height(widget)

            #Gtk.rectangle(ctx, 0, 0, w, h)
            #Gtk.set_source_rgb(ctx, 1, 1, 1)
            Gtk.fill(ctx)

            plot(ctx, w, h)
        end

        #function value_changed(widget::Gtk.GtkScale)
        #    global canvas
        #    draw(canvas)
        #end

        set_gtk_property!(parEstWin, :double_buffered, false)

        #signal_connect(value_changed, sl, "value_changed")
        canvas.draw = draw

        if plotStatus == 0
            parEstFrame2Grid[1,1] = canvas
        end

        plotStatus = 1
        visible(canvas, true)
        showall(parEstWin)
    end
```

Please help me. Any suggestion would be really appreciated. 

Kelvyn

**Comment by lobingera** [comment]
@Kelvyn88 Can you please explain, what the solution was?

**Comment by Kelvyn88** [comment]
Sorry!! I didn´t find any solution. I used Winston instead.
