### ISSUE TITLE
Latex in labels?

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#440]
Hi, its me again.

Is there a way to use latex code in buttons or treeview. This would be definitely a powerful tool to enhance the GUI developed in GTK.

Best,
Kelvyn

**Comment by tknopp** [comment]
That is a question for Gtk itself and not for the Julia bindings.

**Comment by lobingera** [comment]
... still it's a valid question for julia users. 
I see two ways: 
* choose a good Unicode font and just put the label text
* render Latex labels to bitmap and use this.

**Comment by Kelvyn88** [comment]
Thanks for the suggestion @lobingera
