### ISSUE TITLE
xkbcommon: ERROR: failed to add default include path /workspace/destdir/share/X11/xkb

### ISSUE THREAD

**Issue by Wieke** [JuliaGraphics/Gtk.jl#469]
Hi Everyone

Since updating to the latest version I'm getting an error related to the location of `xkb` for some reason it expects that directory to exists at `/workspace/destdir/share/X11/xkb` but it exists at `/usr/share/X11/xkb`. Maybe there's some config somewhere missing on my system I'm not sure, maybe it's the particular build of Gtk on my system, or maybe it's Gtk.jl, but either way I've found the proper solution, setting the `XKB_CONFIG_ROOT` environment variable to the proper location. You could do that like this in your julia code:

```julia
ENV["XKB_CONFIG_ROOT"] = "/usr/share/X11/xkb"
using Gtk
```
(I'm submiting this on the off chance someone else runs into the same issue. I was composing an issue anyway and stumbled upon the solution while double checking something.)

Cheers,

Wieke

**Comment by giordano** [comment]
I'm on it: https://github.com/JuliaPackaging/Yggdrasil/issues/297
