### ISSUE TITLE
GtkFixed?

### ISSUE THREAD

**Issue by caseykneale** [JuliaGraphics/Gtk.jl#477]
https://github.com/JuliaGraphics/Gtk.jl/blob/e243036be95857c5b5c7330fcc0ef91d320d84d3/src/layout.jl#L124

Is there a reason this container is considered bad? Does it go against design decisions in the library? For me, having fixed coords for widgets can be highly beneficial.

**Comment by lobingera** [comment]
According to https://developer.gnome.org/gtk3/stable/GtkFixed.html GtkFixed has many restrictions and GtkLayout can do the same.

**Comment by tknopp** [comment]
@caseykneale: For general gtk question you can ask at the Gnome discourse forum: https://discourse.gnome.org
