### ISSUE TITLE
Render Gadfly plots to Canvas

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#481]
Hi, me again. 

I´m trying to render plots to canvas. I want to use Gadfly, my example is as follows, but it throws an error:
```
using Gtk.ShortNames
using Random
using Gadfly

# Environmental variable to allow Windows decorations
ENV["GTK_CSD"] = 0

c = Canvas()
w = Window(c, "Test Gadfly")
Gtk.showall(w)

p = plot(y=randn(50))
display(c, p)

```

Error: no method matching display(::GtkCanvas, ::Plot)

I tried Immerse but it is required to use an older version of Julia (current is 1.3.1)

**Comment by lobingera** [comment]
I once contributed to Compose/Gadfly an option to render to an already established Cairo surface, which was easy to do, because internally most output devices are Cairo surfaces. I'm not sure this still exists. 

What does the documentation of Gadfly and Immerse mention about using 'display'?

**Comment by jonathanBieler** [comment]
I've made a new release of Immerse that should work on v1.3 a few days ago (you might have to add Cairo to you environment if it complains at precompile).

But otherwise I think you mainly have to call `Compose.draw`, although I don't quite understand all the details here :

https://github.com/JuliaGraphics/Immerse.jl/blob/master/src/display_gadfly.jl#L135

**Comment by Kelvyn88** [comment]
Hi @jonathanBieler , the newest version for Immerse is 1.0.0. Check the following lines (Win10 x64)


(v1.3) pkg> add Immerse
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Immerse [2a4eff87]:
 Immerse [2a4eff87] log:
 ├─possible versions are: [0.1.0-0.1.1, 1.0.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 1.0.0]
 ├─restricted by compatibility requirements with FixedPointNumbers [53c48c17] to versions: 0.1.0-0.1.1 or uninstalled, leaving only versions: 0.1.0-0.1.1
 │ └─FixedPointNumbers [53c48c17] log:
 │   ├─possible versions are: [0.5.0-0.5.3, 0.6.0-0.6.1, 0.7.0-0.7.1] or uninstalled
 │   └─restricted to versions 0.6.1 by an explicit requirement, leaving only versions 0.6.1
 └─restricted by compatibility requirements with Gtk [4c0ca9eb] to versions: 1.0.0 or uninstalled — no versions left
   └─Gtk [4c0ca9eb] log:
     ├─possible versions are: [0.16.0-0.16.5, 0.17.0, 0.18.0, 1.0.0, 1.1.0-1.1.2] or uninstalled
     └─restricted to versions 1.1.2 by an explicit requirement, leaving only versions 1.1.2

**Comment by Kelvyn88** [comment]
@lobingera I didn´t know how to use Gadfly in Gtk. I used display for Winston, that´s the reason why I´m asking for an example with Gadfly. 

Thanks.
