### ISSUE TITLE
Link on label dows not work

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#482]
Hi, 

I just put a link in a labeltext, but I am getting the error:

(julia.exe:21752): Gtk-WARNING **: 00:35:12.625: Couldn't export handle, unsupported windowing system

(julia.exe:21752): Gtk-WARNING **: 00:35:12.645: Unable to show 'https://github.com/JuliaChem/MetDynamic.jl': Fall¾ al leer desde el conducto hijo (EOF)

(Sorry for the words in spanish)

**Comment by jonathanBieler** [comment]
What are you running exactly, this works fine for me :

```julia
usin Gtk
l = GtkLabel("https://developer.gnome.org/gtk3/stable/GtkLabel.html")
w = GtkWindow("")
push!(w,l)
showall(w)
```

**Comment by Kelvyn88** [comment]
using Gtk.ShortNames
ENV["GTK_CSD"] = 0
w = Window()
set_gtk_property!(w, :title, "About")
set_gtk_property!(w, :window_position, 3)
set_gtk_property!(w, :width_request, 100)

g1 = Grid()
set_gtk_property!(g1, :column_spacing, 30)
set_gtk_property!(g1, :row_spacing, 30)
set_gtk_property!(g1, :margin_bottom, 30)
set_gtk_property!(g1, :margin_top, 30)
set_gtk_property!(g1, :column_homogeneous, true)
set_gtk_property!(g1, :row_homogeneous, false)
set_gtk_property!(g1, :margin_left, 30)
set_gtk_property!(g1, :margin_right, 30)

cl = Button("Close")
signal_connect(cl, :clicked) do widget
    destroy(w)
end

label1 = Label(" ")
GAccessor.markup(label1,"""Free available at GitHub:
<a href=\"https://github.com/JuliaChem/SimBioReactor.jl"
title=\"Clic to download\">https://github.com/JuliaChem/SimBioReactor.jl</a>""")
GAccessor.justify(label1, Gtk.GConstants.GtkJustification.CENTER)

g1[1,1] = label1
g1[1,2] = cl

push!(w,g1)

showall(w)

**Comment by Kelvyn88** [comment]
This is my code:

`using Gtk.ShortNames
ENV["GTK_CSD"] = 0
w = Window()
set_gtk_property!(w, :title, "About")
set_gtk_property!(w, :window_position, 3)
set_gtk_property!(w, :width_request, 100)

g1 = Grid()
set_gtk_property!(g1, :column_spacing, 30)
set_gtk_property!(g1, :row_spacing, 30)
set_gtk_property!(g1, :margin_bottom, 30)
set_gtk_property!(g1, :margin_top, 30)
set_gtk_property!(g1, :column_homogeneous, true)
set_gtk_property!(g1, :row_homogeneous, false)
set_gtk_property!(g1, :margin_left, 30)
set_gtk_property!(g1, :margin_right, 30)

cl = Button("Close")
signal_connect(cl, :clicked) do widget
    destroy(w)
end

label1 = Label(" ")
GAccessor.markup(label1,"""Free available at GitHub:
<a href=\"https://github.com/JuliaChem/SimBioReactor.jl"
title=\"Clic to download\">https://github.com/JuliaChem/SimBioReactor.jl</a>""")
GAccessor.justify(label1, Gtk.GConstants.GtkJustification.CENTER)

g1[1,1] = label1
g1[1,2] = cl

push!(w,g1)

showall(w)`

**Comment by Kelvyn88** [comment]
By the way, that code used to work in previous versions of Gtk.
