### ISSUE TITLE
Compatibility with PyPlot?

### ISSUE THREAD

**Issue by henry2004y** [JuliaGraphics/Gtk.jl#493]
I asked this initially on discourse, [cannot import Gtk and PyPlot together?](https://discourse.julialang.org/t/error-when-using-pyplot-and-gtk-package/34559)

I found [this issues](https://github.com/JuliaGraphics/Gtk.jl/issues/193) in the old threads, is it somehow related to my problem?

**Comment by tknopp** [comment]
ping @giordano. Seems an issue that is expected, correct? incompatible versions of the same lib loaded into the same process.

**Comment by giordano** [comment]
Yes, that's quite likely

**Comment by tknopp** [comment]
ok, thanks. So this is a won't fix from our side. It is, by the way, the reason why I am using Gtk+Winston.

**Comment by timholy** [comment]
@henry2004y, did you try the WebAgg backend for PyPlot as in the issue you linked?

**Comment by giordano** [comment]
I wonder if there is a way to convince `PyPlot` to use `GTK3_jll`

**Comment by tknopp** [comment]
Maybe, but as Tim indicates there are simpler workarounds.
