### ISSUE TITLE
(julia.exe:7396): Gtk-WARNING **: 21:07:31.246: Could not load a pixbuf from icon theme.

### ISSUE THREAD

**Issue by IgorFomenko** [JuliaGraphics/Gtk.jl#497]
julia> using Gtk
┌ Warning: You are using Gtk on Windows which is currently not recommended. Your REPL/IDE and anything depending on task switches will become sluggish and much slower (up to ~85x slower).
└ @ Gtk C:\Users\Игорь\.juliapro\JuliaPro_v1.3.1-2\packages\Gtk\X3A4U\src\Gtk.jl:74

julia> win = GtkWindow("My First Gtk.jl Program", 400, 200)

(julia.exe:7396): Gtk-WARNING **: 21:07:31.246: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Users\╚уюЁ№\.juliapro\JuliaPro_v1.3.1-2\artifacts\a940c3d6be54ec6a074c99180694bc9d01b638bd\share\icons\Adwaita\16x16/status\image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_BREAKPOINT at 0x7ffecbd40192 -- DebugBreak at C:\Windows\System32\KERNELBASE.dll (unknown line)
in expression starting at none:0
DebugBreak at C:\Windows\System32\KERNELBASE.dll (unknown line)
Allocations: 34787847 (Pool: 34779442; Big: 8405); GC: 36

Julia has exited.
Press Enter to start a new session.

**Comment by giordano** [comment]
In #461 we found that having Cyrillic (or probably any non ASCII) characters in the PATH causes a lot of problems to Gtk on Windows.  I see that you have "Игорь" as user name, so this can likely be a source of troubles, not sure if this is the main problem though

**Comment by IgorFomenko** [comment]
Thanks, is there something like
   PYTHONIOENCODING=UTF-8
to resolve this problem?

**Comment by giordano** [comment]
No idea, but this is a Gtk issue, not a Julia one :confused:

**Comment by IgorFomenko** [comment]
Ok, I`ve renamed my profile folder, now I`ve got this error
julia> win = GtkWindow("My First Gtk.jl Program", 400, 200)

(julia.exe:12620): Gtk-WARNING **: 08:56:36.651: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Users\Igor\.juliapro\JuliaPro_v1.3.1-2\artifacts\a940c3d6be54ec6a074c99180694bc9d01b638bd\share\icons\Adwaita\16x16/status\image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_BREAKPOINT at 0x7ffecbd40192 -- DebugBreak at C:\Windows\System32\KERNELBASE.dll (unknown line)
in expression starting at none:0
DebugBreak at C:\Windows\System32\KERNELBASE.dll (unknown line)
Allocations: 49639839 (Pool: 49627786; Big: 12053); GC: 51

**Comment by IgorFomenko** [comment]
conda had paths to old profile folder and didn`t work, so,  I've reinstalled Julia, now everything works well
