### ISSUE TITLE
Consistent way to access slider values?

### ISSUE THREAD

**Issue by duncanam** [JuliaGraphics/Gtk.jl#506]
Hello,

Currently it seems that everything I've been playing with can get values with the `get_gtk_property()` function. However, after considerable digging I've found that I need to do a two-step process in order to get GTKScale slider entries, first grabbing `GAccessor.adjustment()` of the slider and then doing a get property. Is this doable with just `get_gtk_property()`? In the GTK+ 3 docs, I'm not seeing GTKScale itself even have the value available [in the properties](https://developer.gnome.org/gtk3/stable/GtkScale.html#GtkScale.properties), so does this mean it's not possible to directly access it? It's not a huge issue, but I do like the consistency and readability of the single function to grab values and `GAccessor.adjustment()` is difficult for me to understand upon first glance.

**Comment by tknopp** [comment]
What property are you referring to in the `GtkScale` docs? As far as I understand it, the value from the scale can only be obtained from the adjustment. I usually do all the UI in Glade and generate an Adjustment for each scale, that I can then use directly in Julia. Just one `get_property` necessary then. That is actually the strength of the concept. One can simple change the graphical representation of the Adjustment to a SpinButton without any changes in Code. If you prefer code, you can also generate the Scale/SpinButton from an existing Adjustment.

**Comment by duncanam** [comment]
In short, I was trying to see if it was possible to access the GTKScale value directly with `get_gtk_property()`, but I'm now seeing that GTK does something a little different with sliders and the `GAccessor.adjustment(slider)` + `get_gtk_property(previous thing)` is required in order to get the value. This is fine, and it looks like from your suggestions with Glade then it becomes fairly straightforward. Thanks.
