### ISSUE TITLE
Method to remove columns in treeview

### ISSUE THREAD

**Issue by Ph0non** [JuliaGraphics/Gtk.jl#514]
In my search through the documentation, I did not find a way to delete columns from a tree view at Gtk.jl, although the Gtk documentation provides a function for this. My suggestion would be to take this naive from the `push!` function and adapt it

```
function deleteat!(treeView::GtkTreeView, treeColumns::GtkTreeViewColumn...)
    for col in treeColumns
        ccall((:gtk_tree_view_remove_column, libgtk), Nothing, (Ptr{GObject}, Ptr{GObject}), treeView, col)
    end
    treeView
end
```

**Comment by tknopp** [comment]
Yes we certainly have not wrapped everything. Please go ahead, test this and make a pull request. Please also add a test to the UI tests (where the tree view is used, starting from https://github.com/JuliaGraphics/Gtk.jl/blob/master/test/gui.jl#L625). Thanks!
