### ISSUE TITLE
Executable file 

### ISSUE THREAD

**Issue by luanvehe9123** [JuliaGraphics/Gtk.jl#522]
Hello, I am programming a simulator in julia, but I need to do an executable file (. Ex), what package is avaible to do it?

Thank you

**Comment by tknopp** [comment]
https://github.com/JuliaLang/PackageCompiler.jl  probably (have not tried)

**Comment by jonathanBieler** [comment]
I tried to make an executable using PackageCompiler before and I managed to make it work. It was before we used BinaryProvider so there was a lot of problems with hard-coded absolute paths, but I think it should be better now with the new system.

**Comment by LilithHafner** [comment]
There is not a great way to do this. Work is ongoing, and there is some discussion here: https://discourse.julialang.org/t/how-to-create-an-exe-file-from-julia-code/30004, but still no satisfactory solution.

Nevertheless, I think this issue can be closed here as out of scope for this repository.
