### ISSUE TITLE
Editable Cell in TreeView

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Gtk.jl#532]
Does anybody know how to make a cell editable in a treeview?

I was available to set the editable property and works, but whem I press enter the value becomes the original. 

Thanks

**Comment by tknopp** [comment]
I have done this for a ListStore / TreeView, here is the basic logic:
```
  store = ListStore(String,...)
  r = CellRendererText()
  set_gtk_property!(r, :editable, true)
  c = TreeViewColumn(col, r, Dict("text" => 0))
  G_.sort_column_id(c,0)
  G_.resizable(c,true)
  signal_connect(r, "edited") do widget, path, text
      # now you can do something with `string(text)`, which is the new text
  end
```

**Comment by Kelvyn88** [comment]
Thanks!! It works!

**Comment by Kelvyn88** [comment]
@tknopp a final question. How can I include a ComboBox to display values when editing a cell un the treeview. I know that the function CellRendererCombo exists but I couldn't find a code example.

**Comment by tknopp** [comment]
I have not used a CellRendererCombo before. Thus I cannot provide working code for that unfortunately.
