### ISSUE TITLE
Generate julia code using GLib

### ISSUE THREAD

**Issue by sa-** [JuliaGraphics/Gtk.jl#538]
Hey all,

How was this file generated? https://github.com/JuliaGraphics/Gtk.jl/blob/master/gen/gbox2

Is it possible to generate such code for other libraries from their typelib files? I'm looking specifically at Apache Arrow, which provides typelib files.

**Comment by tknopp** [comment]
these files are done using Clang.jl and reading header files. This approach should work for all C libraries. Since the script files are a little bit older, the currently do not run with current Julia. Here is a PR to get them going again: https://github.com/JuliaGraphics/Gtk.jl/pull/535

**Comment by sa-** [comment]
Thanks! I'll close this issue
