### ISSUE TITLE
Issue with GError() do error_check

### ISSUE THREAD

**Issue by sa-** [JuliaGraphics/Gtk.jl#539]
When running this code block:

```julia
GError() do error_check
    println("hi")
end
```

I run into this error:
```julia
MethodError: no method matching !(::Nothing)
Closest candidates are:
  !(!Matched::Missing) at missing.jl:100
  !(!Matched::Bool) at bool.jl:33
  !(!Matched::Function) at operators.jl:896

Stacktrace:
 [1] GError(::var"#3#4") at .../GLib/gerror.jl:13
```

I would obviously like to wrap the error check code block around a ccall, but I'm not sure what's wrong here. Am I doing something wrong?

**Comment by vtjnash** [comment]
You need to actually do an error check and return the result. Here you're ignoring `error_check` and returning `nothing`.

**Comment by sa-** [comment]
Thanks for the quick response - I was looking at your GLib repo earlier this week.

I tried to emulate my GError code block by looking at this piece of code:
https://github.com/JuliaGraphics/Gtk.jl/blob/8f06e467ac66bbf464445a8f9f126829f848b882/src/theme.jl#L14-L18

This is what my code actually looks like
```
GError() do error_check
    ccall(
        (:gparquet_arrow_file_reader_new_path, "/usr/local/Cellar/apache-arrow-glib/2.0.0/lib/libparquet-glib.200"), 
        Ptr{GObject}, 
        (Ptr{UInt8}, Ptr{Ptr{GError}}), 
        Gtk.bytestring(path), error_check
    )
end
```

And I am greeted with the same error :(
```
MethodError: no method matching !(::Ptr{GObject})
Closest candidates are:
  !(!Matched::Missing) at missing.jl:100
  !(!Matched::Bool) at bool.jl:33
  !(!Matched::Function) at operators.jl:896
```

**Comment by jonathanBieler** [comment]
@sa- I think the do block needs to return a Bool, see e.g. here :

https://github.com/JuliaGraphics/Gtk.jl/blob/66ca486d6c15199ff027afa833653c4bf217ea24/src/builder.jl#L17

I think the error you see comes from that line : 

https://github.com/JuliaGraphics/Gtk.jl/blob/4190f445872257e7fdf92c96409e48a00380785c/src/GLib/gerror.jl#L13

**Comment by sa-** [comment]
Thanks that fixed everything!
