### ISSUE TITLE
How can I change the color of a label?

### ISSUE THREAD

**Issue by MasFlam** [JuliaGraphics/Gtk.jl#559]
I have a label and I want the foreground color of it to be green or red at different times. This isn't a gtk property and so I don't really know how I can change it. In glade I can just choose it as one of the attributes and in the generated xml it is also named an attribute but I can't find any functions with that in their name.

**Comment by LinCloud** [comment]
GAccessor.markup(widget, "<span background=\"green\">your label</span>")

**Comment by LinCloud** [comment]
```
GAccessor.markup(widget, "<span background=\"green\">" * label * "</span>")
```

**Comment by LinCloud** [comment]
```
GAccessor.markup(widget, "<span foreground=\"green\">" * label * "</span>")
```

**Comment by MasFlam** [comment]
Thanks
