### ISSUE TITLE
macOS Installation Steps?

### ISSUE THREAD

**Issue by spencerking** [JuliaGraphics/Gtk.jl#564]
Are there recommended installation steps for Mac users? I do not see any in the documentation. I have installed Gtk.jl with `Pkg` and installed Gtk3 with Homebrew: `brew install gtk+3`. When I try to run:
```
using Gtk

win = GtkWindow("My First Gtk.jl Program", 400, 200)

b = GtkButton("Click Me")
push!(win,b)

showall(win)
```

I do not see any output. No window appears and no errors are logged in the terminal.

**Comment by tknopp** [comment]
you do not need to install via brew. And what you should see is window popping up. Have just tried and here it works.

**Comment by spencerking** [comment]
@tknopp Do you have any advice on how to debug this issue? When I check my pkg status I can see that `[4c0ca9eb] Gtk v1.1.6` is installed. I have the code from my first post in a file `example.jl` and when I run `julia example.jl` nothing happens.

**Comment by tknopp** [comment]
That is supposed to happen. You need to startup Julia and then `include("example.jl")`. If that works, there is also a section in the manual how you can start a Gtk application with `julia example.jl` (you need to prevent Julia prom terminating)

**Comment by spencerking** [comment]
Ah I see, thank you for your help
