### ISSUE TITLE
Documentation not being generated

### ISSUE THREAD

**Issue by tknopp** [JuliaGraphics/Gtk.jl#566]
Not sure if this ever worked with Github actions but right now it fails:

https://github.com/JuliaGraphics/Gtk.jl/runs/2054338675?check_suite_focus=true

**Comment by timholy** [comment]
See https://github.com/julia-actions/MassInstallAction.jl/blob/master/demos/MaintenanceDec2020/maintenance.jl for all kinds of goodies for updating most/all of the infrastructure supporting a package.

**Comment by tknopp** [comment]
yes, but does that here help? I mean the infrastructure is already up to date ins't it? The error is
```
xvfb-run: error: Xvfb failed to start
192
Error: Process completed with exit code 1.
```

**Comment by giordano** [comment]
@saschamann any clue why xvfb doesn't work anymore?

**Comment by SaschaMann** [comment]
No idea, sorry.

I don't really know xvfb, perhaps check [actions/virtual-environments](https://github.com/actions/virtual-environments/) for recent updates to its package?

I've had builds fail for random non-Julia reasons before due errors in the ubuntu packages. Usually those fixed themselves after a week when a new image was rolled out.

**Comment by giordano** [comment]
The first builds worked, then it started to fail without us changing anything :confused:  So yeah, changes in the environments of the runners may be the culprit here.

**Comment by tknopp** [comment]
I have re-run the actions and now it builds...

**Comment by giordano** [comment]
@SaschaMann the weird thing is that `xvfb-run` works without issues in `julia-runtest`, but it fails in `julia-docdeploy` (yes, it failed again: https://github.com/JuliaGraphics/Gtk.jl/pull/569/checks?check_run_id=2070269831).  Is there anything different between the workflows?

**Comment by giordano** [comment]
It also goes without saying that in tmate it works flawless
![image](https://user-images.githubusercontent.com/765740/110552189-c5af2280-812e-11eb-8949-b65eaca9c6ad.png)

**Comment by SaschaMann** [comment]
I don't think so. The jobs run on identical GHA runner versions and in identical virtual environments too.

These are the commands that are executed in those actions:

- https://github.com/julia-actions/julia-docdeploy/blob/master/action.yml#L15-L40
- https://github.com/julia-actions/julia-runtest/blob/master/action.yml#L27-L56

In the `test` job in the workflow in this repo, `julia-buildpkg`, which runs `Pkg.build()`, does not have the `xvfb-run` prefix. In the `Documentation` job, the instantiation (`Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'`) is run with the `xvfb-run` prefix. It's a bit of a stretch, but maybe there's some interaction that causes issues during building/instantiating the package?

As I said, I don't know `xvfb-run` at all, I'm purely guessing based on the commands that are executed in the actions/workflows.
