### ISSUE TITLE
Don't set custon fontconfig

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaGraphics/Gtk.jl#574]
It seems that setting a different fontconfig prevents using emoji fonts in GTK Entry, among other issues
GTK.jl should not override system fontconfig

**Comment by giordano** [comment]
Do you mean the `FONTCONFIG_FILE` and `FONTCONFIG_PATH` environment variables?  They are set in https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/blob/4a774dc6b40531890eb0cc37b09976802ac1bbf1/src/wrappers/x86_64-linux-gnu.jl#L80-L81 and they do _not_ override system defaults if those variables are already set.

**Comment by DhruvaSambrani** [comment]
Oh, right.

However, hitting ctrl+. in an Entry widget shows the emoji popup, but no emojis are actually rendered. Other gtk apps work, so its not a system wide issue. The UI was made with glade, and running `glade-previewer` with the glade file works fine too. So the only layer which could be causing the issue is GTK.jl

**Comment by giordano** [comment]
I mean, you need to set `FONTCONFIG_FILE` to the desired value to ensure your system fontconfig is used.  What `Fontconfig_jll` does it to provide a default in case there are no other options.
