### ISSUE TITLE
Problems when doing multi-threading

### ISSUE THREAD

**Issue by sletz** [JuliaGraphics/Gtk.jl#585]
I'm trying to use PortAudio.jl in an application where the running audio code control parameters have to be updated in real-time with a GTK based GUI.

The PA template code is here: https://github.com/grame-cncm/faust/blob/master-dev/architecture/julia/audio/portaudio.jl

The GTK Controller code is here: https://github.com/grame-cncm/faust/blob/master-dev/architecture/julia/gui/GTKUI.jl
 
I need to start the GTKUI code, make it do not block the calling thread, and have the PortAudio audio rendering code  start later on. 

I tris using `Threads.@spawn` without success: the GTK windows does not show correctly and cannot be used. Any idea?

**Comment by tknopp** [comment]
Its not really clear to me, what you are doing. Do you run Julia in interactive mode or in non-interactive mode?

What works:
- start Julia in interactive mode and run it with two threads.
- run the worker thread using `@tspawnat 2` from https://github.com/tro3/ThreadPools.jl. Usually one will spawn the thread in a callback.

**Comment by sletz** [comment]
More to less working now, thanks.
