### ISSUE TITLE
Changing Gtk theme

### ISSUE THREAD

**Issue by StefanMathis** [JuliaGraphics/Gtk.jl#586]
Hello,

I'm currently developing a GUI with GTK.jl and I'd like to change the theme at runtime (e.g. to the win32 theme when the program is executed on Windows). Is there an easy way to do this? I searched quite a bit on the web and found for example this explanation on how to do it with Python:
https://stackoverflow.com/questions/42881112/pygtk3-how-to-change-application-theme

However, as far as I understand, the themes for Gtk.jl are provided by the .jll packages in the main Gtk.jl file. Does this mean that for any specific theme a .jll-Package needs to be built? Furthermore, how can one select a specific theme? For example, in Gtk.jl the following packages are imported:
`adwaita_icon_theme_jll, hicolor_icon_theme_jll`
From the look and feel, I'd say that the Adwaita theme is used by default, however I could not identify where in the code this is actually specified.

Any help would be appreciated very much :-)

**Comment by tknopp** [comment]
Could you try setting it using an environment variable? See https://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis

**Comment by tknopp** [comment]
Yes this works
```
GTK_THEME=Adwaita:dark julia
```
makes all widgets dark.

**Comment by StefanMathis** [comment]
Thank you very much for your answer. I found this stackexchange comment as well, however I'm not sure how to set a environment variable at runtime of the Julia program. Or is this simply not possible / desirable?

**Comment by tknopp** [comment]
I think there is also some possibility to do this at runtime within Gtk but actually this solution with the environment variable and the `__init__` function is also fine from my perspective.

**Comment by StefanMathis** [comment]
I didn't test it, but I think you can actually change the theme at runtime because `__init__` is just a function :-)
