### ISSUE TITLE
Dialog windows sometimes not doing anything on v1.1.11

### ISSUE THREAD

**Issue by Vexatos** [JuliaGraphics/Gtk.jl#610]
The changes introduced in PR #607 seem to cause issues when showing dialog boxes sometimes, at least on Windows. Setting `GTK_AUTO_IDLE` to `false` fixes it, confirming that this PR is the culprit.

We don't have much information to present unfortunately, but in some situations, opening a dialog box such as `ask_dialog` shortly after `using Gtk` opens a completely unresponsive window. It's not possible to interact with any buttons in the window, including the X button in the window bar. In our tests, adding a simple `sleep(0)` or `println()` in front of the `ask_dialog` is already enough to fix it, so we don't really know why this could happen.

**Comment by IanButterworth** [comment]
Thanks. I'm looking into this

**Comment by IanButterworth** [comment]
I don't have access to a windows machine and I can't reproduce this on ubuntu by just doing
```
julia> begin
           using Gtk
           ask_dialog("hello")
       end
```

@Vexatos would you mind dev-ing Gtk and trying to add a `yield()` between line 41 and 42 here?
https://github.com/JuliaGraphics/Gtk.jl/blob/cea01ebcabead4dd26fccfde0a5bb22071dce0b5/src/base.jl#L41

If that doesn't work try between 40 and 41.

Sorry for the breakage!

**Comment by Vexatos** [comment]
Putting a `yield()` after the `signal_connect` block does indeed appear to reliably fix the issue.
