### ISSUE TITLE
Multiple monitors

### ISSUE THREAD

**Issue by DylanMMarques** [JuliaGraphics/Gtk.jl#631]
Hello,

I am trying to create a Gtk window on the secondary screen. However, I am not sure how to do that. In Python, the function `get_n_monitors()` is available but I haven't found in Julia. Is there such a function in julia? Also, the function `screen_size()` returns `(1920, 1200)` if only one screen is connect but `(4248, 1710)` if multiple screens are connected via HDMI. The resolution of the screens connected are `(1920, 1200)` and `(912, 1140)`

The documentation of `screen_size()` is very poor so I am not sure what it is meant to return. But I am not sure what `(4248, 1710)` is.

Thanks

**Comment by giordano** [comment]
It doesn't look like [`get_n_monitors`](https://docs.gtk.org/gdk3/method.Screen.get_n_monitors.html) is wrapped by `Gtk.jl`, but you can call it yourself like this:
```julia
julia> screen = @ccall Gtk.libgdk.gdk_screen_get_default()::Ptr{Cvoid}
Ptr{Nothing} @0x00000000025d6020

julia> @ccall Gtk.libgdk.gdk_screen_get_n_monitors(screen::Ptr{Cvoid})::Cint
2
```
I have an external monitor connected, and it's correctly detecting there are two monitors available.

**Comment by lobingera** [comment]
Correctly identifying monitors is not available on all OS and depending on the setting of your display system (e.g. X11, xrandr) not even possible and might be subject to your window manager.

**Comment by StefanPofahl** [comment]
Hi Dylan,
thanks for this peace of code!
Can you post an example how to put "[Message Dialog Box](https://juliagraphics.github.io/Gtk.jl/latest/manual/filedialogs/)" on the same monitor where vscode is located?
Regards,
Stefan

**Comment by StefanPofahl** [comment]
Command: [`gdk-screen-get-n-monitors`](http://transit.iut2.upmf-grenoble.fr/doc/libgtk-3-doc/gdk3/GdkScreen.html#gdk-screen-get-n-monitors) is deprecated, use [`gdk_display_get_n_monitors()`](http://transit.iut2.upmf-grenoble.fr/doc/libgtk-3-doc/gdk3/GdkDisplay.html#gdk-display-get-n-monitors) instead.
