### ISSUE TITLE
I get the following report when using Gtk.selected_rows()

### ISSUE THREAD

**Issue by johntrinder** [JuliaGraphics/Gtk.jl#632]
I am using the code supplied in the docs but have had to search around for using multiple selections in a TreeView
The code portion I have used is:
...
selection = GAccessor.selection(trvw) # a GtkTreeSelectionLeaf
selection = GAccessor.mode(selection,Gtk.GConstants.GtkSelectionMode.MULTIPLE) 

signal_connect(selection, "changed") do widget
    if  hasselection(selection)
      global currentIt = Gtk.selected_rows(selection) # crashes REPL
      println(currentIt)
      # global currentIt = selected(selection)
      # ix = Gtk.index_from_iter(str, currentIt)
      # # now you can to something with the selected item
      # println("index=$ix  Text: ", str[currentIt,1], "\nImage: ", str[currentIt,2])
    end
  end
...

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x27248e0 -- gc_mark_loop at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:2529
in expression starting at none:0
gc_mark_loop at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:2529
_jl_gc_collect at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3039
jl_gc_collect at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3248
maybe_collect at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:882 [inlined]
jl_gc_pool_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:1209
jl_gc_alloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_internal.h:339 [inlined]
jl_gc_alloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3290
_new_array_ at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:127 [inlined]
_new_array at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:193 [inlined]
jl_alloc_array_1d at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:441
Array at .\boot.jl:457 [inlined]
Array at .\boot.jl:476 [inlined]
getindex at .\array.jl:411 [inlined]
compute_live_ins at .\compiler/ssair\slot2ssa.jl:526
construct_ssa! at .\compiler/ssair\slot2ssa.jl:633
slot2reg at .\compiler\optimize.jl:419 [inlined]
run_passes at .\compiler\optimize.jl:303
optimize at .\compiler\optimize.jl:296 [inlined]
_typeinf at .\compiler\typeinfer.jl:255
typeinf at .\compiler\typeinfer.jl:209
abstract_call_method_with_const_args at .\compiler\abstractinterpretation.jl:557
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:113
abstract_call_known at .\compiler\abstractinterpretation.jl:1342
abstract_call at .\compiler\abstractinterpretation.jl:1397
abstract_call at .\compiler\abstractinterpretation.jl:1382
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1534
typeinf_local at .\compiler\abstractinterpretation.jl:1918
typeinf_nocycle at .\compiler\abstractinterpretation.jl:2014
_typeinf at .\compiler\typeinfer.jl:226
typeinf at .\compiler\typeinfer.jl:209
typeinf_edge at .\compiler\typeinfer.jl:823 [inlined]
abstract_call_method at .\compiler\abstractinterpretation.jl:504
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:105
abstract_call_known at .\compiler\abstractinterpretation.jl:1342
abstract_call at .\compiler\abstractinterpretation.jl:1397
abstract_call at .\compiler\abstractinterpretation.jl:1382
abstract_eval_statement at .\compiler\abstractinterpretation.jl:1534
typeinf_local at .\compiler\abstractinterpretation.jl:1918
typeinf_nocycle at .\compiler\abstractinterpretation.jl:2014
_typeinf at .\compiler\typeinfer.jl:226
typeinf at .\compiler\typeinfer.jl:209
typeinf_ext at .\compiler\typeinfer.jl:909
typeinf_ext_toplevel at .\compiler\typeinfer.jl:942
typeinf_ext_toplevel at .\compiler\typeinfer.jl:938
jfptr_typeinf_ext_toplevel_12223.clone_1 at C:\Users\Daddy\AppData\Local\Programs\Julia-1.7.1\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2247 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2429 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:295
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:338
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1980
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1934 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2239 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2429
#handle_message#49 at c:\Users\Daddy\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\VSCodeServer\src\progress.jl:19
handle_message at c:\Users\Daddy\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\VSCodeServer\src\progress.jl:5
unknown function (ip: 000000005fdf18c4)
macro expansion at .\logging.jl:365 [inlined]
blame at C:\Users\Daddy\.julia\packages\Gtk\vBOOU\src\GLib\signals.jl:106
macro expansion at C:\Users\Daddy\.julia\packages\Gtk\vBOOU\src\GLib\signals.jl:220 [inlined]
#94 at .\task.jl:423
unknown function (ip: 000000005fdf09b3)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:877
Allocations: 19111509 (Pool: 19103293; Big: 8216); GC: 22

**Comment by jwahlstrand** [comment]
The crash in `selected_rows` was recently fixed (#620) but hasn't been released yet. I think a release will happen soon. Hopefully that will solve your issue.

**Comment by johntrinder** [comment]
Thankyou

**Comment by tknopp** [comment]
release is triggered
