### ISSUE TITLE
Don't write to package directory

### ISSUE THREAD

**Issue by maleadt** [JuliaGraphics/Gtk.jl#667]
Gtk.jl currently, during `__init__`, writes to its own package directory: https://github.com/JuliaGraphics/Gtk.jl/blob/1924a815e3ed42212c2ad0d375aee1de61c7ed8b/src/Gtk.jl#L93

This is not OK, as packages may be installed in a system-wide or otherwise read-only location. Gtk.jl should use Scratch.jl to get a directory to write temporary things to.

**Comment by tknopp** [comment]
https://github.com/JuliaGraphics/Gtk.jl/pull/619

**Comment by maleadt** [comment]
Oh ok, sorry for the noise.
