### ISSUE TITLE
Connecting event to calendar

### ISSUE THREAD

**Issue by rossati** [JuliaGraphics/Gtk.jl#673]
Hi
I am new on Julia and 
I am trying to use the GTK Calendar:
```
using GTK3_jll 
const libgtk = libgtk3
using Gtk, Gtk.ShortNames
function fnz(x)
    println("$x")
end
win = GtkWindow( "Try Calendar")
c = ccall((:gtk_calendar_new,libgtk), Ptr{GObject}, (Ptr{UInt8},),"")
push!(win,c)
z = showall(win)
return ""
```
The problem arises when I try to link the **day-selected** signal to a Julia function:
## First attempt ##
via **g_signal_connect** function
```
fnz_c = @cfunction(fnz,Cvoid,(Ref{String},))
ccall((:g_signal_connect,libgtk),Ptr{GObject},(Ptr{GObject},Ptr{GObject},Ptr{Cvoid}),c,"day-selected",fnz_c)
```
I obtain **could not load symbol "g_signal_connect"** and I not found where the function is declared.
## Second attempt ##
via gtk.jl **signal_connect** function
```
id = signal_connect(fnz, c, "day-selected")
```
In this case the error is: **no method matching signal_connect** that I suppose for **c** is a **::Ptr{GObject}** and the function needs **::GObject**, but I not know how transform  a **::Ptr{GObject}** into a **::GObject**.
Thanks for any sggestions
Giovanni Rossati

**Comment by tknopp** [comment]
```
c = convert(GObject, ccall((:gtk_calendar_new,libgtk), Ptr{GObject}, (Ptr{UInt8},),""))
```
Or generate the widget with GtkBuilder.

**Comment by rossati** [comment]
Very thank TKnopp
So with GtkBuilder I can easy access to widget non covered by Gtk.jl?

**Comment by tknopp** [comment]
exectly. They will be considered to be `GtkWidget` and with that you can do already quite a lot.

**Comment by rossati** [comment]
I tried, it works very well with file created by Glade, but the GtkBulder by the same string of file doesn't works.
My be is an old problem because i seen an unanswered request on  [StackOwerflow](https://stackoverflow.com/questions/71355262/julia-gtk-gtkbuilder-gtkbuilderbuffer-astring-error).
