### ISSUE TITLE
Where is gdk library

### ISSUE THREAD

**Issue by rossati** [JuliaGraphics/Gtk.jl#675]
Hi
I'm trying to add CSS styling at the Screen level, but I can't figure out where certain functions are declared, for example `gdk_display_get_default`.
I tried with the library `gdk_pixbuf_jll` but, assuming it contains the function mentioned above, I don't know the name to use in the `ccall`.
Thanks

**Comment by jwahlstrand** [comment]
It's bundled with libgtk3, see GTK3_jll.libgdk3
